### ISSUE TITLE
Remove e-mail notifications issued from dspadmin@princeton.edu for DataSpace import procedures

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#131]
This is a DSpace account which should default to either the NetID of the user importing the Items, or me.

**Comment by kmcelwee** [comment]
Highest priority is the server errors @matthewjchandler will paste the email message.

**Comment by matthewjchandler** [comment]
As of 2021-02-02, we've received over 100,000 server error emails. We understand we shouldn't be worried about the substance of the messages, but the quantity is concerning.

**Comment by matthewjchandler** [comment]
Example: 


An internal server error occurred on https://dataspace.princeton.edu:

Date:       2/3/21 8:42 AM
Session ID: FB35A6A031FA9ACC2CF9655A4E669093
User:       Anonymous
IP address: 10.246.0.2

-- URL Was: https://dataspace.princeton.edu/bitstream/88435/dsp010v8383358/1/Takahashi_princeton_0181D_12808.pdf
-- Method: GET
-- Parameters were:


Exception:
org.apache.catalina.connector.ClientAbortException: java.net.SocketException: Connection reset
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:411)
	at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:451)
	at org.apache.tomcat.util.buf.ByteChunk.append(ByteChunk.java:352)
	at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:436)
	at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:424)
	at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:91)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
	at org.dspace.core.Utils.copy(Utils.java:238)
	at org.dspace.core.Utils.bufferedCopy(Utils.java:264)
	at org.dspace.app.webui.servlet.BitstreamServlet.doDSGet(BitstreamServlet.java:158)
	at org.dspace.app.webui.servlet.DSpaceServlet.processRequest(DSpaceServlet.java:130)
	at org.dspace.app.webui.servlet.DSpaceServlet.doGet(DSpaceServlet.java:75)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.dspace.utils.servlet.DSpaceWebappServletFilter.doFilter(DSpaceWebappServletFilter.java:78)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:165)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:317)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at org.apache.coyote.ajp.AjpProcessor.output(AjpProcessor.java:298)
	at org.apache.coyote.ajp.AbstractAjpProcessor$SocketOutputBuffer.doWrite(AbstractAjpProcessor.java:1305)
	at org.apache.coyote.Response.doWrite(Response.java:578)
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:406)
	... 37 more

**Comment by kmcelwee** [comment]
In dataspace, the config file is `princeton-5/prod.properties`. I believe we need to change:
```
# Recipient for server errors and alerts
#mail.alert.recipient = email-address-here
mail.alert.recipient= dspaceadmin@princeton.libanswers.com
```
Double checking with Atmire that changing this won't cause unexpected errors.

@matthewjchandler please confirm whether or not dspaceadmin@princeton.libanswers.com is forwarded to dspaceadmin@princeton.edu.

**Comment by matthewjchandler** [comment]
Sorry, I don't know what those email addresses are. The only email address I'm aware of is dspadmin@princeton.edu

**Comment by kmcelwee** [comment]
I've just sent an email to dspaceadmin@princeton.libanswers.com testing whether it's aliased to dspadmin@princeton.edu

Would you mind checking dspadmin@princteon.edu for an email with the subject line "TEST FROM KEVIN"?

**Comment by matthewjchandler** [comment]
Nothing within 10 minutes, so these addresses are probably not aliases

**Comment by kmcelwee** [comment]
A meeting with Atmire was met with a shrug, that this is the inevitable consequence of being the admin account email. Atmire recommends an email filter.
