### ISSUE TITLE
Troubleshoot and document the solution for authentication issues on the Symplectic Elements QA and Production environments

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#171]

**Comment by jrgriffiniii** [comment]
Connecting over the PowerShell requires the following:
```powershell
$sqlConn = New-Object System.Data.SqlClient.SqlConnection
$sqlConn.ConnectionString = "Data Source=CISDR300W;Initial Catalog=elements;Integrated Security=False;User ID=Sympsql_Dev;Password=[SECRET]"
$sqlConn.Open()
```

**Comment by jrgriffiniii** [comment]
This may be unrelated, but `rt4ds` does not appear to be accessible for the OAR `dev` server:
![image](https://user-images.githubusercontent.com/1443986/91943597-d76cc480-ecca-11ea-8eaa-a847f08a5ad0.png)

**Comment by jrgriffiniii** [comment]
There are only two configuration files on the OIT server infrastructure for the `rt4ds` service which are not symbolic links to DSpace installation files. These do not seem to have any significantly different settings: https://gist.github.com/jrgriffiniii/d7f61d19d938ae82b3301f39b0ac6494

**Comment by jrgriffiniii** [comment]
The logs for `rt4ds` were being generated until 08/18/20:

```
dspace@gcp-oar-dev1:/dspace/log$ ls -lt | grep rt4ds
-rw-rw-r--  1 dspace dspace   1050629 Aug 18 13:33 rt4ds.log.99
-rw-rw-r--  1 dspace dspace   1052263 Aug 18 13:33 rt4ds.log.98
```

**Comment by jrgriffiniii** [comment]
`/home/dspace/apache-tomcat/conf/logging.properties` on `gcp-oar-dev1` and `/etc/tomcat/logging.properties` on `cisdr204l.princeton.edu` are essentially identical between server environments (with the exception of UTF-8 support for `gcp-oar-dev1`)

**Comment by jrgriffiniii** [comment]
`/dspace/rt4ds/config/log4j.properties` is properly in place on `gcp-oar-dev1`, but the logs are not being generated - is this expected behavior?

**Comment by jrgriffiniii** [comment]
Once tomcat was started, the following was logged:

```
INFO: Deploying deployment descriptor [/home/dspace/apache-tomcat-7.0.104/conf/Catalina/localhost/rt4ds.xml]
Sep 02, 2020 1:56:42 PM org.apache.catalina.loader.WebappClassLoaderBase validateJarFile
INFO: validateJarFile(/mnt/disks/oardevdatastore/prod-copy/dspace/webapps.static/rt4ds/WEB-INF/lib/servlet-api-2.5.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class
Sep 02, 2020 1:56:43 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://java.sun.com/jstl/fmt is already defined
Sep 02, 2020 1:56:44 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://java.sun.com/jstl/fmt is already defined
Sep 02, 2020 1:56:44 PM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Sep 02, 2020 1:56:51 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deployment of deployment descriptor [/home/dspace/apache-tomcat-7.0.104/conf/Catalina/localhost/rt4ds.xml] has finished in [9,040] ms
```

**Comment by jrgriffiniii** [comment]
Within `/dspace/webapps.static/rt4ds/META-INF/maven/org.dspace.modules/rt4ds/pom.xml`, version `2.4` was specified for the JAR:

```
<dependency>
                   <groupId>javax.servlet</groupId>
                   <artifactId>servlet-api</artifactId>
                   <version>2.4</version>
                   <scope>provided</scope>
                </dependency>
```

I updated this to 2.5. but the error persisted.

**Comment by jrgriffiniii** [comment]
A number of `/dspace/dspace-rt4ds.cfg` and `/dspace/dspace.cfg` settings were outdated or incorrect for communicating with the Elements server.

**Comment by jrgriffiniii** [comment]
`oar-dev.princeton.edu` will need to be able to access `oaworkflow-dev.princeton.edu`, and this seems to be prevented by firewall rules. This has been requested with https://princeton.service-now.com/service?id=ticket&is_new_order=true&table=incident&sys_id=9764a5c91b8f1410b69cca292a4bcb1b

**Comment by jrgriffiniii** [comment]
https://princeton.service-now.com/service?id=ticket&table=change_request&sys_id=068669c51bcf1410b69cca292a4bcbff&view=sp was created for the production environment.

**Comment by jrgriffiniii** [comment]
https://princeton.service-now.com/service?id=ticket&is_new_order=true&table=incident&sys_id=245d9e951bc75010b69cca292a4bcb7b has now superceded the previous requests in order to migrate the Elements servers into a new VLAN for public IP address.

**Comment by jrgriffiniii** [comment]
https://princeton.service-now.com/service?id=ticket&table=change_request&sys_id=e1d3d0e11bd71410435885d56b4bcb11&view=sp and https://princeton.service-now.com/service?id=ticket&table=change_request&sys_id=f2c69c651b1b1410435885d56b4bcb23&view=sp are needed in order to enable traffic between the OAR and Elements servers over the ports 9002 and 9090.

**Comment by jrgriffiniii** [comment]
While the ports are opened, the `rt4ds` Tomcat app. has not been deployed on the `staging` or `dev` environments.

**Comment by jrgriffiniii** [comment]
At this point, there are transport-layer issues affecting the ability for clients on the Elements servers to be able to communicate with PULibrary web servers. I have been evaluating and testing the various instructions specified on https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls, along with using https://gist.github.com/jrgriffiniii/3bb229955645f17a36bc3e0560add9b5 in an attempt to diagnose these connectivity problems.

I am now attempting to restart the `dev` server in order to use updated Windows registry values. Should this prove to be ineffective, I will need to resort to exclusively relying upon OIT for support and assistance.

**Comment by jrgriffiniii** [comment]
https://princeton.service-now.com/service?id=ticket&table=incident&sys_id=09ed2bbf1b6fd010435885d56b4bcbec&view=sp was created after another attempt at resolving these issues myself.

**Comment by jrgriffiniii** [comment]
https://princeton.service-now.com/service?id=ticket&table=task&sys_id=5629dcec1b4c64108c9ebbb21a4bcbad unblocked a significant obstacle to establishing connections over the TLS between the servers.

**Comment by jrgriffiniii** [comment]
While the Windows Server VMs can connect to the OAR servers using HTTP clients over TLS in the browser, the following error message is still logged for the server:

![image](https://user-images.githubusercontent.com/1443986/96726651-2e645100-1380-11eb-98ca-c1c7685d66f9.png)

**Comment by jrgriffiniii** [comment]
This has been advanced to Symplectic with the following support request: https://support.symplectic.co.uk/support/tickets/318716

**Comment by jrgriffiniii** [comment]
When requesting https://oar-dev.princeton.edu/rt4ds/repository, the OAR installation attempts to connect to the Elements server. This connection fails from within the OAR server environment with the following:

```bash
2020-10-27 09:40:21,047 ERROR uk.co.symplectic.elements.servlets.RepositoryServlet @ Caught ClientAbortException
org.apache.catalina.connector.ClientAbortException: java.net.SocketException: Connection reset
        at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:411)
```

Please note that this is a *separate* error from what is raised when the Elements server attempts to deposit a submission into the OAR installation.

**Comment by jrgriffiniii** [comment]
The following is logged on the load balancer for the OAR server node when attempting to establish a request from the Elements Windows Server:

```
TLS handshake error: handshake failed: error:140260C1:SSL routines:ACCEPT_SR_CLNT_HELLO:no shared cipher: Invalid argument
```

**Comment by jrgriffiniii** [comment]
https://github.com/libressl-portable/openbsd/blob/master/src/lib/libssl/ssl_err.c#L317 is the error code for this on the server side.

**Comment by jrgriffiniii** [comment]
This is now blocked by https://github.com/pulibrary/dspace-development/issues/204

**Comment by jrgriffiniii** [comment]
`rt4ds` is still not running for the production, and quite a number of configuration files needed to be adjusted for this.

Currently, the error which is now blocking this is:
```
SEVERE: The web application [/rt4ds] registered the JDBC driver [org.postgresql.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
```

**Comment by jrgriffiniii** [comment]
https://github.com/DSpace/DSpace/blob/dspace-5.5/dspace-api/src/main/java/org/dspace/app/util/AbstractDSpaceWebapp.java#L98 is now where there is a blocking error being raised, with the following stack trace:

```
SEVERE: Exception sending context destroyed event to listener instance of class [org.dspace.app.util.DSpaceContextListener]
java.lang.NullPointerException
        at org.dspace.storage.rdbms.DatabaseManager.delete(DatabaseManager.java:784)
        at org.dspace.app.util.AbstractDSpaceWebapp.deregister(AbstractDSpaceWebapp.java:98)
        at org.dspace.app.util.DSpaceContextListener.contextDestroyed(DSpaceContextListener.java:146)
        at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:5174)
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5865)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:187)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1007)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:983)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:639)
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:712)
        at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:2001)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by jrgriffiniii** [comment]
I suspect that https://github.com/DSpace/DSpace/blob/dspace-5.5/dspace-api/src/main/java/org/dspace/app/util/AbstractDSpaceWebapp.java#L80 is where there was supposed to be a database record created for the `rt4ds` module, but for some reason it was not.

**Comment by jrgriffiniii** [comment]
There were a number of errors still within the configuration file for `rt4ds` (which were erroneously copied from the production environment). Testing for and addressing these deployed `rt4ds`:

![image](https://user-images.githubusercontent.com/1443986/98976424-54939180-24e5-11eb-9586-6d557d7748b3.png)

**Comment by jrgriffiniii** [comment]
I have just successfully tested this for the `production` environment, and this has fixed the Item synchronization:

![image](https://user-images.githubusercontent.com/1443986/98977790-04b5ca00-24e7-11eb-8016-1f375a8d46cd.png)

**Comment by jrgriffiniii** [comment]
This is no longer affecting the Elements deployments.
