### ISSUE TITLE
DataSpace Items cannot be committed to the archive for the `dev` environment

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#175]
When attempting to commit an Item to the archive, the following error is raised:

![image](https://user-images.githubusercontent.com/1443986/92201250-11180980-ee4a-11ea-9e99-4d049cf2ddbd.png)

**Comment by jrgriffiniii** [comment]
The following stack trace was present:

```
Exception:
java.lang.RuntimeException: Error while attempting to create identifier for Item id: 105927
        at org.dspace.identifier.HandleIdentifierProvider.register(HandleIdentifierProvider.java:82)
        at org.dspace.identifier.IdentifierServiceImpl.register(IdentifierServiceImpl.java:83)
        at org.dspace.content.InstallItem.installItem(InstallItem.java:70)
        at org.dspace.content.InstallItem.installItem(InstallItem.java:44)
        at org.dspace.workflow.WorkflowManager.archive(WorkflowManager.java:724)
...
Caused by: java.lang.RuntimeException: Error while attempting to create identifier for Item id: 105927
        at org.dspace.identifier.HandleIdentifierProvider.mint(HandleIdentifierProvider.java:130)
        at org.dspace.identifier.HandleIdentifierProvider.register(HandleIdentifierProvider.java:70)
```

**Comment by jrgriffiniii** [comment]
This might be a regression from https://github.com/pulibrary/dspace-development/issues/99#issuecomment-668359402

**Comment by jrgriffiniii** [comment]
The following was necessary in `/dspace/config/dspace.cfg`:

```
  # handle.prefix = 88435
  handle.prefix = 99999

  # This plus the ARK identifier is stored as the persistent URI of the Item
  handle.canonical.prefix = http://arks.princeton.edu/ark:/

  # These are configuration parameters for the EZID ARK minting service
  ark.ezid_server = https://ezid.cdlib.org
  ark.ezid_username = apitest
  ark.ezid_password = apitest
  ark.shoulder = fk4
```
