### ISSUE TITLE
Add DataSpace arks to MARC records for September 2019 ETDs

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dspace-development#197]
Using the list from Lynn's email on 10/14, add arks from DataSpace to the marc records attached ([steps 7 - 9 in the workflow](https://docs.google.com/document/d/16zv87K9LiTGE5nlngtwbrVyKCxUOkPvRqA1_ig9Lsis/edit#)).

**Comment by jrgriffiniii** [comment]
As specified in https://princeton.service-now.com/nav_to.do?uri=%2Fsc_task.do%3Fsys_id%3Dc5f978651b60e410435885d56b4bcb30, I have tested and currently do have the proper permissions for the CIFS share needed to upload the MARC records.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/dspace-cli/compare/jrgriffiniii-senior-theses-restructure...pulibrary:jrgriffiniii-cli-java was needed in order to port the Java CLI tasks into the production environment (these are used to process the MARC records). Currently, I am working to resolve the following error:

```bash
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/marc4j/marc/VariableField
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.marc4j.marc.VariableField
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 7 more
```

**Comment by jrgriffiniii** [comment]
The updated ProQuest metadata has been generated, however there are still cases where the ARKs were not matched. I will need to proceed with this by inserting these manually using the `MARC Tools`.

**Comment by jrgriffiniii** [comment]
The updated MARC records were placed into the CIFS share for upload into Voyager. I will update this once I have confirmation that the records have been updated in the ILS (if I recall correctly, this takes place daily at midnight).

**Comment by jrgriffiniii** [comment]
These records do not appear to have been imported, I will request support from colleagues in EUS.

**Comment by jrgriffiniii** [comment]
Following a discussion with an EUS colleague, I have submitted a SN@P support request (lsupport) in order to advance troubleshooting  this.

**Comment by jrgriffiniii** [comment]
This is now being tracked with https://princeton.service-now.com/service?sys_id=3cde35e81b4160108c9ebbb21a4bcbde&view=sp&id=ticket&table=sc_req_item

**Comment by jrgriffiniii** [comment]
After requesting for assistance privately from colleagues in the EUS, it was discovered that this was due to a file-formatting error. The records now have the updated DataSpace ARKs (please see https://bibdata.princeton.edu/bibliographic/12229747 and https://catalog.princeton.edu/catalog/12229747)
