### ISSUE TITLE
Troubleshoot and resolve Solr reindexing issues for the DataSpace staging environment

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#203]
The following error messages were logged for the DataSpace staging environment:

```bash
Error opening new searcher,trace=org.apache.solr.common.SolrException: SolrCore 'search' is not available due to init failure: Error
 opening new searcher
        at org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:745)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:299)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:207)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.dspace.solr.filters.LocalHostRestrictionFilter.doFilter(LocalHostRestrictionFilter.java:50)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:165)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1201)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:317)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.solr.common.SolrException: Error opening new searcher
        at org.apache.solr.core.SolrCore.&lt;init&gt;(SolrCore.java:873)
        at org.apache.solr.core.SolrCore.&lt;init&gt;(SolrCore.java:646)
        at org.apache.solr.core.CoreContainer.create(CoreContainer.java:491)
        at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:255)
        at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:249)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more
Caused by: org.apache.solr.common.SolrException: Error opening new searcher
        at org.apache.solr.core.SolrCore.openNewSearcher(SolrCore.java:1565)
        at org.apache.solr.core.SolrCore.getSearcher(SolrCore.java:1677)
        at org.apache.solr.core.SolrCore.&lt;init&gt;(SolrCore.java:845)
        ... 8 more
Caused by: java.nio.file.NoSuchFileException: /mnt/disks/dataspacetestdatastore/prod-copy/dspace/solr/search/data/index/segments_o2vn
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
        at java.nio.channels.FileChannel.open(FileChannel.java:287)
        at java.nio.channels.FileChannel.open(FileChannel.java:335)
        at org.apache.lucene.store.MMapDirectory.openInput(MMapDirectory.java:196)
        at org.apache.lucene.store.NRTCachingDirectory.openInput(NRTCachingDirectory.java:198)
        at org.apache.lucene.store.Directory.openChecksumInput(Directory.java:113)
        at org.apache.lucene.index.SegmentInfos.read(SegmentInfos.java:341)
        at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:454)
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:906)
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:752)
        at org.apache.lucene.index.SegmentInfos.read(SegmentInfos.java:450)
        at org.apache.lucene.index.IndexWriter.&lt;init&gt;(IndexWriter.java:792)
        at org.apache.solr.update.SolrIndexWriter.&lt;init&gt;(SolrIndexWriter.java:77)
        at org.apache.solr.update.SolrIndexWriter.create(SolrIndexWriter.java:64)
        at org.apache.solr.update.DefaultSolrCoreState.createMainIndexWriter(DefaultSolrCoreState.java:279)
        at org.apache.solr.update.DefaultSolrCoreState.getIndexWriter(DefaultSolrCoreState.java:111)
        at org.apache.solr.core.SolrCore.openNewSearcher(SolrCore.java:1528)
        ... 10 more
```

This prevents Items, Collections, and Communities from being reindexed.

**Comment by vab** [comment]
This is typically a file permissions problem (specifically a lock file) problem with your solr search index directory.

If you're running a solr instance for your DSpace install on a separate server, you should verify that that system is running correctly and that the solr instance can read and write to the directory where the search collection for your dspace system is located.

If you're running a solr instance for your DSpace install locally with in the same Tomcat (or Jetty) instance (like most people), you need to do the same thing. In this case, your solr search index (and other indexes) would be located in ${dspace.dir}/solr. For search specifically, ${dspace.dir}/solr/search and for the actual index files ${dspace.dir}/solr/search/data/index . Make sure that Tomcat can write to these directories and create new files. Typically, file ownership permissions, where the Tomcat/DSpace user cannot write to the ${dspace.dir}/solr directory and its subdirectories is the problem.

If file permissions are not the problem, you may have stale lock files. Solr, in the default DSpace installs, defaults to "native" locking. However, it includes options in its configuration to use "simple" (lock file existence) locks and even to clear all locks on start-up. It also includes "single" locking that should not be used with DSpace. Simple locking is fine for DSpace in my experience. However, using the "clear all locks" option as part of your regular configuration can be dangerous.

If you suspect a stale lockfile problem, shutdown Tomcat and remove all files named "write.lock" in all subdirectories of ${dspace.dir}/solr . Then, restart Tomcat, and attempt to update your search indexes (bash$ dspace index-discovery). Note, if you did not ever successfully create your search indexes in the first place, you should probably run index-discovery with a '-b' flag which will "(re)build index, wiping out current one if it exists".

If you still see file locking issues and are sure your file permissions/ownership are correct, try switching your solr collections to "simple" locking. You can find this setting in ${dspace.dir}/solr/(collection)/conf/solrconfig.xml. You can also find the "clear all locks" setting in this file. To apply it, shutdown Tomcat, remove all write.lock files, and restart Tomcat. Then attempt to update your search indexes.

If this still doesn't work, try setting "clear all locks" for all your solr collections, shutdown tomcat, remove any write.lock files, and restart tomcat. Then, try running index-discovery again. Note: If this does work, you'll want to shutdown tomcat afterward and disable the "clear all locks" setting.

Finally, if none of this works, it's possible that your DSpace home directory isn't being set properly and that the solr webapp for DSpace is therefor not configured with proper directory location for the solr directory. If that is the case, it wouldn't be able to find the indexes in order to open or update them. This is configured in your local.cfg, your dspace.cfg, and in your solr webapp directory at ${tomcat.home}/webapps/solr/WEB-IMF/web.xml file. Setting in your local.cfg should be sufficient. The value stored in web.xml is taken from the dspace.cfg file in src/dspace/config/dspace.cfg during the build process. You can directly set your solr home in that web.xml file in the <env-entry> object. However, if the web.xml file is incorrect, the web.xml files would be incorrect for all the DSpace webapps.

**Comment by jrgriffiniii** [comment]
Thank you very much @vab !!! I apologize for having failed to return to this issue. It has since stopped occurring due, and should be resolved.
