### ISSUE TITLE
Complete the DataSpace September 2019 ETD importation

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#23]
As reported:

```
Sept. 2019 import of ETD did not include all of the ETDs from the batch (see the attached document which shows that some were imported and some were not-- we did not search the entire list)
```

**Comment by jrgriffiniii** [comment]
This should inform how best to work with importing ETDs and provide an opportunity for documenting more of this process.

**Comment by jrgriffiniii** [comment]
The following dissertations were found on the SFTP server for Autumn 2019:

```
-rw-r--r--    1 98041    pusvc     7515921 Oct  4  2019 etdadmin_upload_693053.zip
--
-rw-r--r--    1 98041    pusvc     3747590 Oct  4  2019 etdadmin_upload_693059.zip
-rw-r--r--    1 98041    pusvc     3954404 Oct  4  2019 etdadmin_upload_692592.zip
-rw-r--r--    1 98041    pusvc     6203836 Oct  4  2019 etdadmin_upload_692647.zip
-rw-r--r--    1 98041    pusvc     2016583 Oct  4  2019 etdadmin_upload_692732.zip
-rw-r--r--    1 98041    pusvc     8599442 Oct  4  2019 etdadmin_upload_692479.zip
-rw-r--r--    1 98041    pusvc     3360504 Oct  4  2019 etdadmin_upload_692521.zip
-rw-r--r--    1 98041    pusvc     3869248 Oct  4  2019 etdadmin_upload_692208.zip
-rw-r--r--    1 98041    pusvc     3665753 Oct  4  2019 etdadmin_upload_692404.zip
-rw-r--r--    1 98041    pusvc    228634027 Oct  4  2019 etdadmin_upload_692074.zip
-rw-r--r--    1 98041    pusvc     3192312 Oct  4  2019 etdadmin_upload_692136.zip
-rw-r--r--    1 98041    pusvc    23363852 Oct  4  2019 etdadmin_upload_691663.zip
-rw-r--r--    1 98041    pusvc     5048954 Oct  4  2019 etdadmin_upload_692022.zip
-rw-r--r--    1 98041    pusvc    22858051 Oct  4  2019 etdadmin_upload_691659.zip
-rw-r--r--    1 98041    pusvc    19604735 Oct  4  2019 etdadmin_upload_691529.zip
-rw-r--r--    1 98041    pusvc    12146679 Oct  4  2019 etdadmin_upload_691555.zip
-rw-r--r--    1 98041    pusvc     2177478 Oct  4  2019 etdadmin_upload_691603.zip
-rw-r--r--    1 98041    pusvc    57906891 Oct  4  2019 etdadmin_upload_691031.zip
-rw-r--r--    1 98041    pusvc     3265229 Oct  4  2019 etdadmin_upload_691086.zip
-rw-r--r--    1 98041    pusvc    14537635 Oct  4  2019 etdadmin_upload_691303.zip
-rw-r--r--    1 98041    pusvc     3745670 Oct  4  2019 etdadmin_upload_690526.zip
-rw-r--r--    1 98041    pusvc     2557675 Oct  4  2019 etdadmin_upload_690532.zip
-rw-r--r--    1 98041    pusvc     4097274 Oct  4  2019 etdadmin_upload_690703.zip
-rw-r--r--    1 98041    pusvc     2391605 Oct  4  2019 etdadmin_upload_690761.zip
-rw-r--r--    1 98041    pusvc     1010369 Oct  4  2019 etdadmin_upload_690798.zip
-rw-r--r--    1 98041    pusvc      893229 Oct  4  2019 etdadmin_upload_690897.zip
-rw-r--r--    1 98041    pusvc    28684259 Oct  4  2019 etdadmin_upload_690237.zip
-rw-r--r--    1 98041    pusvc     3218568 Oct  4  2019 etdadmin_upload_690266.zip
-rw-r--r--    1 98041    pusvc     3101292 Oct  4  2019 etdadmin_upload_690382.zip
-rw-r--r--    1 98041    pusvc     1047744 Oct  4  2019 etdadmin_upload_690523.zip
-rw-r--r--    1 98041    pusvc    113176421 Oct  4  2019 etdadmin_upload_690187.zip
-rw-r--r--    1 98041    pusvc    13264386 Oct  4  2019 etdadmin_upload_689558.zip
-rw-r--r--    1 98041    pusvc     2396523 Oct  4  2019 etdadmin_upload_689636.zip
-rw-r--r--    1 98041    pusvc     1740527 Oct  4  2019 etdadmin_upload_689665.zip
-rw-r--r--    1 98041    pusvc     4527197 Oct  4  2019 etdadmin_upload_689299.zip
-rw-r--r--    1 98041    pusvc     6184444 Oct  4  2019 etdadmin_upload_689331.zip
-rw-r--r--    1 98041    pusvc    12128580 Oct  4  2019 etdadmin_upload_688507.zip
-rw-r--r--    1 98041    pusvc     1323027 Oct  4  2019 etdadmin_upload_689115.zip
-rw-r--r--    1 98041    pusvc    13836670 Oct  4  2019 etdadmin_upload_689180.zip
-rw-r--r--    1 98041    pusvc     6940085 Oct  4  2019 etdadmin_upload_687775.zip
-rw-r--r--    1 98041    pusvc     1590799 Oct  4  2019 etdadmin_upload_688038.zip
-rw-r--r--    1 98041    pusvc    14614300 Oct  4  2019 etdadmin_upload_687501.zip
-rw-r--r--    1 98041    pusvc     6006746 Oct  4  2019 etdadmin_upload_687525.zip
-rw-r--r--    1 98041    pusvc    159048700 Oct  4  2019 etdadmin_upload_687311.zip
-rw-r--r--    1 98041    pusvc     3928148 Oct  4  2019 etdadmin_upload_687395.zip
-rw-r--r--    1 98041    pusvc    40542413 Oct  4  2019 etdadmin_upload_687301.zip
-rw-r--r--    1 98041    pusvc    10765422 Oct  4  2019 etdadmin_upload_685967.zip
-rw-r--r--    1 98041    pusvc      520941 Oct  4  2019 etdadmin_upload_685522.zip
-rw-r--r--    1 98041    pusvc     7517254 Oct  4  2019 etdadmin_upload_685678.zip
-rw-r--r--    1 98041    pusvc     1582407 Oct  4  2019 etdadmin_upload_685690.zip
-rw-r--r--    1 98041    pusvc    683140771 Oct  4  2019 etdadmin_upload_685085.zip
-rw-r--r--    1 98041    pusvc     1272996 Oct  4  2019 etdadmin_upload_685362.zip
-rw-r--r--    1 98041    pusvc    39532004 Oct  4  2019 etdadmin_upload_685019.zip
-rw-r--r--    1 98041    pusvc     1144723 Oct  4  2019 etdadmin_upload_685022.zip
-rw-r--r--    1 98041    pusvc    112349784 Oct  4  2019 etdadmin_upload_685001.zip
-rw-r--r--    1 98041    pusvc     1836805 Oct  4  2019 etdadmin_upload_684957.zip
-rw-r--r--    1 98041    pusvc    17335146 Oct  4  2019 etdadmin_upload_684020.zip
-rw-r--r--    1 98041    pusvc     4600255 Oct  4  2019 etdadmin_upload_684057.zip
-rw-r--r--    1 98041    pusvc    15660144 Oct  4  2019 etdadmin_upload_683709.zip
-rw-r--r--    1 98041    pusvc     1750924 Oct  4  2019 etdadmin_upload_683315.zip
-rw-r--r--    1 98041    pusvc     2750618 Oct  4  2019 etdadmin_upload_683351.zip
-rw-r--r--    1 98041    pusvc     4938925 Oct  4  2019 etdadmin_upload_682687.zip
-rw-r--r--    1 98041    pusvc     8296846 Oct  4  2019 etdadmin_upload_682903.zip
-rw-r--r--    1 98041    pusvc     2418017 Oct  4  2019 etdadmin_upload_682293.zip
-rw-r--r--    1 98041    pusvc    27411097 Oct  4  2019 etdadmin_upload_681979.zip
-rw-r--r--    1 98041    pusvc    50324447 Oct  4  2019 etdadmin_upload_681851.zip
-rw-r--r--    1 98041    pusvc     2275692 Oct  4  2019 etdadmin_upload_681427.zip                                                                                                      [160/1503]
-rw-r--r--    1 98041    pusvc     3598823 Oct  4  2019 etdadmin_upload_681153.zip
-rw-r--r--    1 98041    pusvc     4660346 Oct  4  2019 etdadmin_upload_681385.zip
-rw-r--r--    1 98041    pusvc     2300035 Oct  4  2019 etdadmin_upload_680065.zip
-rw-r--r--    1 98041    pusvc     1475614 Oct  4  2019 etdadmin_upload_680193.zip
-rw-r--r--    1 98041    pusvc     1461253 Oct  4  2019 etdadmin_upload_680345.zip
-rw-r--r--    1 98041    pusvc    22554670 Oct  4  2019 etdadmin_upload_678841.zip
-rw-r--r--    1 98041    pusvc     6619902 Oct  4  2019 etdadmin_upload_679710.zip
-rw-r--r--    1 98041    pusvc    172900122 Oct  4  2019 etdadmin_upload_678711.zip
-rw-r--r--    1 98041    pusvc     2489660 Oct  4  2019 etdadmin_upload_678828.zip
-rw-r--r--    1 98041    pusvc    15312352 Oct  4  2019 etdadmin_upload_678134.zip
-rw-r--r--    1 98041    pusvc     8100647 Oct  4  2019 etdadmin_upload_677159.zip
-rw-r--r--    1 98041    pusvc     6453048 Oct  4  2019 etdadmin_upload_677220.zip
-rw-r--r--    1 98041    pusvc    29737396 Oct  4  2019 etdadmin_upload_676609.zip
-rw-r--r--    1 98041    pusvc     3005850 Oct  4  2019 etdadmin_upload_676014.zip
-rw-r--r--    1 98041    pusvc    100185223 Oct  4  2019 etdadmin_upload_676012.zip
-rw-r--r--    1 98041    pusvc    22792561 Oct  4  2019 etdadmin_upload_675912.zip
-rw-r--r--    1 98041    pusvc    44215095 Oct  4  2019 etdadmin_upload_675910.zip
-rw-r--r--    1 98041    pusvc    39324128 Oct  4  2019 etdadmin_upload_675747.zip
-rw-r--r--    1 98041    pusvc    67398840 Oct  4  2019 etdadmin_upload_675667.zip
-rw-r--r--    1 98041    pusvc     1247063 Oct  4  2019 etdadmin_upload_675685.zip
-rw-r--r--    1 98041    pusvc     3869471 Oct  4  2019 etdadmin_upload_675295.zip
-rw-r--r--    1 98041    pusvc     3674533 Oct  4  2019 etdadmin_upload_674632.zip
-rw-r--r--    1 98041    pusvc     6775678 Oct  4  2019 etdadmin_upload_674881.zip
-rw-r--r--    1 98041    pusvc     1830732 Oct  4  2019 etdadmin_upload_674114.zip
-rw-r--r--    1 98041    pusvc    10410248 Oct  4  2019 etdadmin_upload_673536.zip
-rw-r--r--    1 98041    pusvc     1679233 Oct  4  2019 etdadmin_upload_673814.zip
-rw-r--r--    1 98041    pusvc     4750311 Oct  4  2019 etdadmin_upload_673871.zip
-rw-r--r--    1 98041    pusvc    26000689 Oct  4  2019 etdadmin_upload_672989.zip
-rw-r--r--    1 98041    pusvc     1854085 Oct  4  2019 etdadmin_upload_673292.zip
-rw-r--r--    1 98041    pusvc    17194836 Oct  4  2019 etdadmin_upload_672933.zip
-rw-r--r--    1 98041    pusvc    80157978 Oct  4  2019 etdadmin_upload_672827.zip
-rw-r--r--    1 98041    pusvc     3466488 Oct  4  2019 etdadmin_upload_672882.zip
-rw-r--r--    1 98041    pusvc    15693959 Oct  4  2019 etdadmin_upload_672048.zip
-rw-r--r--    1 98041    pusvc    18737726 Oct  4  2019 etdadmin_upload_671867.zip
-rw-r--r--    1 98041    pusvc     3279122 Oct  4  2019 etdadmin_upload_671924.zip
-rw-r--r--    1 98041    pusvc     5551246 Oct  4  2019 etdadmin_upload_671563.zip
-rw-r--r--    1 98041    pusvc     3075144 Oct  4  2019 etdadmin_upload_670433.zip
-rw-r--r--    1 98041    pusvc     4099028 Oct  4  2019 etdadmin_upload_670446.zip
-rw-r--r--    1 98041    pusvc     2384340 Oct  4  2019 etdadmin_upload_670809.zip
-rw-r--r--    1 98041    pusvc    27047732 Oct  4  2019 etdadmin_upload_669766.zip                                                                                                      [120/1503]
-rw-r--r--    1 98041    pusvc     1716836 Oct  4  2019 etdadmin_upload_670074.zip
-rw-r--r--    1 98041    pusvc     1140047 Oct  4  2019 etdadmin_upload_670089.zip
-rw-r--r--    1 98041    pusvc    10770194 Oct  4  2019 etdadmin_upload_669619.zip
-rw-r--r--    1 98041    pusvc    25578811 Oct  4  2019 etdadmin_upload_668630.zip
-rw-r--r--    1 98041    pusvc     9677551 Oct  4  2019 etdadmin_upload_669325.zip
-rw-r--r--    1 98041    pusvc     7683996 Oct  4  2019 etdadmin_upload_667309.zip
-rw-r--r--    1 98041    pusvc     2163401 Oct  4  2019 etdadmin_upload_668025.zip
-rw-r--r--    1 98041    pusvc    23419628 Oct  4  2019 etdadmin_upload_665410.zip
-rw-r--r--    1 98041    pusvc    35045142 Oct  4  2019 etdadmin_upload_663637.zip
-rw-r--r--    1 98041    pusvc    31984570 Oct  4  2019 etdadmin_upload_663599.zip
-rw-r--r--    1 98041    pusvc    31167406 Oct  4  2019 etdadmin_upload_662952.zip
-rw-r--r--    1 98041    pusvc     1420765 Oct  4  2019 etdadmin_upload_663015.zip
```

**Comment by jrgriffiniii** [comment]
Running the Python AIP ingestion script yielded the following:

```
#145 sftp_upload/20200712_october_2019/etdadmin_upload_693837.zip
#145 unzip sftp_upload/20200712_october_2019/etdadmin_upload_693837.zip to import/20200712_october_2019/SUCCESS/etdadmin_upload_693837
#145 make import/20200712_october_2019/SUCCESS/etdadmin_upload_693837/dublin_core.xml
#145 make import/20200712_october_2019/SUCCESS/etdadmin_upload_693837/contents #files 1
#145 make import/20200712_october_2019/SUCCESS/etdadmin_upload_693837/collections
#145 SUCCESS etdadmin_upload_693837

SUCCESS on 145 dissertations
REJECT for 0 dissertations
```

**Comment by jrgriffiniii** [comment]
The following error was encountered:

```
        Schema: dc Element: publisher Qualifier:  Value: Princeton, NJ : Princeton University
        Loading dublin core from /usr/local/DR/home/dspace/dissertations/etd-ingest/import/20200712_october_2019/SUCCESS/etdadmin_upload_675910/metadata_pu.xml
        Schema: pu Element: embargo Qualifier: terms Value: 2020-04-04
        Schema: pu Element: embargo Qualifier: lift Value: 2020-04-04
        Processing contents file: import/20200712_october_2019/SUCCESS/etdadmin_upload_675910/contents
        Bitstream: Lee_princeton_0181D_13095.pdf
Processing handle file: handle
It appears there is no handle file -- generating one
ERROR org.dspace.app.itemimport.ItemImport @ Exception after install item, try to revert...
java.lang.IllegalArgumentException: Embargo lift date must be in the future, but this is in the past: 2020-04-04
        at org.dspace.embargo.EmbargoManager.getEmbargoTermsAsDate(EmbargoManager.java:158)
        at org.dspace.content.InstallItem.populateMetadata(InstallItem.java:165)
        at org.dspace.content.InstallItem.installItem(InstallItem.java:64)
        at org.dspace.app.itemimport.ItemImport.addItem(ItemImport.java:916)
        at org.dspace.app.itemimport.ItemImport.addItems(ItemImport.java:736)
        at org.dspace.app.itemimport.ItemImport.main(ItemImport.java:498)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:607)
        at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
        at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:78)
java.lang.IllegalArgumentException: Embargo lift date must be in the future, but this is in the past: 2020-04-04
        at org.dspace.embargo.EmbargoManager.getEmbargoTermsAsDate(EmbargoManager.java:158)
        at org.dspace.content.InstallItem.populateMetadata(InstallItem.java:165)
        at org.dspace.content.InstallItem.installItem(InstallItem.java:64)
        at org.dspace.app.itemimport.ItemImport.addItem(ItemImport.java:916)
        at org.dspace.app.itemimport.ItemImport.addItems(ItemImport.java:736)
        at org.dspace.app.itemimport.ItemImport.main(ItemImport.java:498)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:607)
        at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
        at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:78)
java.lang.IllegalArgumentException: Embargo lift date must be in the future, but this is in the past: 2020-04-04
Started: 1594605646222
Ended: 1594605694640
Elapsed time: 48 secs (48418 msecs)
```

**Comment by jrgriffiniii** [comment]
These dissertations were imported into the following DSpace Items:

```
etdadmin_upload_662952 88435/dsp018623j1658
etdadmin_upload_663015 88435/dsp014f16c573q
etdadmin_upload_663599 88435/dsp010p096983g
etdadmin_upload_663637 88435/dsp01w0892d850
etdadmin_upload_664000 88435/dsp01r781wj95j
etdadmin_upload_664145 88435/dsp01mg74qq03c
etdadmin_upload_664153 88435/dsp01gq67jv105
etdadmin_upload_664156 88435/dsp01bz60d018d
etdadmin_upload_664162 88435/dsp01765374268
etdadmin_upload_664198 88435/dsp013f4628361
etdadmin_upload_664214 88435/dsp01zs25xc387
etdadmin_upload_664230 88435/dsp01v118rh47r
etdadmin_upload_664241 88435/dsp01q811kn54v
etdadmin_upload_664284 88435/dsp01kh04ds61n
etdadmin_upload_664288 88435/dsp01fq977x69d
etdadmin_upload_664338 88435/dsp019z903278c
etdadmin_upload_664359 88435/dsp016682x6881
etdadmin_upload_664434 88435/dsp012j62s7770
etdadmin_upload_664451 88435/dsp01xs55mf99v
etdadmin_upload_664515 88435/dsp01t148fm05s
etdadmin_upload_664521 88435/dsp01p8418r12w
etdadmin_upload_664528 88435/dsp01jh343w20b
etdadmin_upload_664567 88435/dsp01dr26z1304
etdadmin_upload_664629 88435/dsp019019s539k
etdadmin_upload_665410 88435/dsp015999n631z
etdadmin_upload_667309 88435/dsp011j92gb40c
etdadmin_upload_668025 88435/dsp01ws859j58j
etdadmin_upload_668630 88435/dsp01s1784p65r
etdadmin_upload_669325 88435/dsp01n870zt730
etdadmin_upload_669619 88435/dsp01hh63sz823
etdadmin_upload_669766 88435/dsp01cv43p073x
etdadmin_upload_670074 88435/dsp018336h4833
etdadmin_upload_670089 88435/dsp014b29b8926
etdadmin_upload_670433 88435/dsp010k225d98k
etdadmin_upload_670446 88435/dsp01vt150n18h
etdadmin_upload_670809 88435/dsp01r207ts26v
etdadmin_upload_671563 88435/dsp01m900nx358
etdadmin_upload_671867 88435/dsp01gm80hz24m
etdadmin_upload_671924 88435/dsp01bv73c334x
etdadmin_upload_672048 88435/dsp0173666743f
etdadmin_upload_672827 88435/dsp013b591c49h
etdadmin_upload_672882 88435/dsp01zk51vk69v
etdadmin_upload_672933 88435/dsp01tt44pq779
etdadmin_upload_672989 88435/dsp01q237hv87g
etdadmin_upload_673292 88435/dsp01kd17cw773
etdadmin_upload_673536 88435/dsp01fn107187q
etdadmin_upload_673814 88435/dsp019w0325955
etdadmin_upload_673871 88435/dsp016395wb01z
etdadmin_upload_674114 88435/dsp012b88qg09b
etdadmin_upload_674632 88435/dsp01xk81jp296
etdadmin_upload_674881 88435/dsp01st74ct389
etdadmin_upload_675295 88435/dsp01p5547v30q
etdadmin_upload_675667 88435/dsp01jd4730399
etdadmin_upload_675685 88435/dsp01dn39x446k
etdadmin_upload_675747 88435/dsp018w32r853p
```
