### ISSUE TITLE
Symplectic Element deposits are failing for the production environment

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#305]
This was reported by a member of the Scholarly Collections and Research Services:

```
When I try to deposit things I get an error that says

An error occurred whilst uploading the file to the repository.....
```

**Comment by jrgriffiniii** [comment]
The production environment for the OAR appears to no longer be resolving the `rt4ds` DSpace module, as the following error is logged for deposits:

```
Exception type: System.Web.Http.HttpResponseException
Message: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
Stack trace:
at Symplectic.Foundation.Http.SympHttpClient+<SendAsync>d__16.MoveNext() in libraries\Symplectic.Foundation\Http\SympHttpClient.cs:line 364, char 6
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task)
at Symplectic.Foundation.Http.SympHttpClient+<GetBufferedResponseAsync>d__13.MoveNext() in libraries\Symplectic.Foundation\Http\SympHttpClient.cs:line 266, char 10
at Symplectic.Foundation.Concurrency.AggregateExceptionHandling.RethrowFirstInnerNonAggregateExeption(AggregateException) in libraries\Symplectic.Foundation\Concurrency\AggregateExceptionHandling.cs:line 25, char 4
at Symplectic.Foundation.Concurrency.AggregateExceptionHandling.UnwrapResultingAggregateExceptions<TResult>(Func<TResult>) in libraries\Symplectic.Foundation\Concurrency\AggregateExceptionHandling.cs:line 40, char 5
at Symplectic.Foundation.Http.SympHttpClient.GetBufferedResponse(HttpRequestMessage, Nullable<TimeSpan>) in libraries\Symplectic.Foundation\Http\SympHttpClient.cs:line 244, char 4
at Symplectic.Elements.Repository.Client.Rt1RepositoryClient.UploadFile(ApiRepositoryPublication, Rt1RepositoryFileType, MonitoringStreamCopier, String, String, String, Int64) in elements\Repository.Client\Rt1RepositoryClient.cs:line 519, char 5

HttpResponseException-specific information:
	Request Method: POST
	Request URL: https://oar.princeton.edu/rt4ds/repository
	Response Status Code: 404
	Response Reason Phrase: Not Found
```

**Comment by jrgriffiniii** [comment]
The reporting user has confirmed that service is now restored. However, this really should not be resolved until I create a new issue for documenting this process in https://github.com/pulibrary/dspace-development

**Comment by jrgriffiniii** [comment]
In order to clean the project board, I'm going to proceed with closing this.

**Comment by jrgriffiniii** [comment]
This has reoccurred, and it appears that the `rt4ds` does *not* get redeployed into the production environment when `dsbounce` is invoked.

**Comment by jrgriffiniii** [comment]
Deploying the `rt4ds` required the following changes introduced in the branch `jrgriffiniii-oar-rt4ds-deployment` (please see https://git.atmire.com/clients/princeton-5/-/compare/oar-prod...jrgriffiniii-oar-rt4ds-deployment). While this does now deploy the necessary files into production, there is a new blocking error:

```bash
INFO: Deploying web application directory [/mnt/disks/oarproddatastore/prod-copy/dspace/webapps/rt4ds]
Jun 29, 2021 1:59:45 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error while attempting to validate required application extensions
java.io.IOException: Jar: aopalliance-1.0.jar
        at org.apache.catalina.util.ExtensionValidator.validateApplication(ExtensionValidator.java:205)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5468)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1007)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:983)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:639)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1296)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2037)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.zip.ZipException: invalid block type
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
        at java.util.zip.ZipInputStream.read(ZipInputStream.java:194)
        at java.util.jar.JarInputStream.read(JarInputStream.java:207)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at java.util.jar.JarInputStream.getBytes(JarInputStream.java:112)                                                                                                      
        at java.util.jar.JarInputStream.checkManifest(JarInputStream.java:94)
        at java.util.jar.JarInputStream.<init>(JarInputStream.java:86)
        at java.util.jar.JarInputStream.<init>(JarInputStream.java:62)
        at org.apache.catalina.util.ExtensionValidator.getManifest(ExtensionValidator.java:401)
        at org.apache.catalina.util.ExtensionValidator.validateApplication(ExtensionValidator.java:194)
        ... 12 more
```

**Comment by jrgriffiniii** [comment]
While the JARs seem to be copied to the correct location, copying these from the destination directory for the Tomcat engine yields the following:

```
~/src$ jar tf ~/tmp/asm-commons-4.1.jar
java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.zip.ZipFile.<init>(ZipFile.java:126)
        at sun.tools.jar.Main.list(Main.java:1115)
        at sun.tools.jar.Main.run(Main.java:293)
        at sun.tools.jar.Main.main(Main.java:1288)
```

**Comment by jrgriffiniii** [comment]
Attempting to read from the same JAR files used in other web apps seems to be fine:

```bash
~/src$ cp /dspace/webapps/rest/WEB-INF/lib/asm-commons-4.1.jar ~/tmp/
~/src$ jar tf ~/tmp/asm-commons-4.1.jar
META-INF/MANIFEST.MF
org/objectweb/asm/commons/AdviceAdapter.class
org/objectweb/asm/commons/AnalyzerAdapter.class
```

**Comment by jrgriffiniii** [comment]
Upon further inspection, not all JAR files were affected:

```bash
~/src$ cp /dspace/webapps/rest/WEB-INF/lib/poi-scratchpad-3.6.jar ~/tmp/
~/src$ jar tf ~/tmp/poi-scratchpad-3.6.jar
META-INF/
META-INF/MANIFEST.MF
org/
org/apache/
org/apache/poi/
org/apache/poi/hdf/
org/apache/poi/hdf/event/
org/apache/poi/hdf/extractor/
org/apache/poi/hdf/extractor/data/
org/apache/poi/hdf/extractor/util/
```

**Comment by jrgriffiniii** [comment]
Attempting to clean the Maven cached JAR files did not resolve this issue.

**Comment by jrgriffiniii** [comment]
The configuration for https://maven.apache.org/plugins/maven-assembly-plugin/ now seems to be primarily where the root of this problem lies. This copies JAR files, which, somehow are corrupted before deployment.

**Comment by jrgriffiniii** [comment]
This has been restored with https://git.atmire.com/clients/princeton-5/-/compare/oar-prod...jrgriffiniii-oar-rt4ds-deployment, however there is still one inconsistency with deployment for the underlying `rt4ds/WEB-INF/libs` directory.

**Comment by jrgriffiniii** [comment]
#353 seems to have also been blocking this from being fully resolved. I am not going to resolve this until I have received some confirmation that this is still functioning for the reporting user.
