### ISSUE TITLE
Downloads for DataSpace Bundle 159270 are failing

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#480]
The files could not be download https://dataspace.princeton.edu/retrieve/159270/dataForPNASsubmission.zip:

![image](https://user-images.githubusercontent.com/1443986/134061022-d134d273-bbcf-4991-9032-fe131bbd3759.png)

**Comment by jrgriffiniii** [comment]
This is related to a file-system level permissions issue:

```bash
2021-09-20 14:49:54,348 ERROR org.dspace.app.webui.servlet.DSpaceServlet @ jrg5@princeton.edu:session_id=9273DD094D273CA64C419930DC15BCF7:ip_ad
dr=137.83.219.136:unhandled error:java.io.FileNotFoundException\colon; /mnt/disks/dataspaceproddatastore/prod-copy/assetstore_production/13/49/
66/134966057684743006473428354266837213174 (Permission denied)
java.io.FileNotFoundException: /mnt/disks/dataspaceproddatastore/prod-copy/assetstore_production/13/49/66/1349660576847430064734283542668372131
74 (Permission denied)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at edu.sdsc.grid.io.local.LocalFileInputStream.open(LocalFileInputStream.java:171)
        at edu.sdsc.grid.io.GeneralFileInputStream.<init>(GeneralFileInputStream.java:145)                                                             at edu.sdsc.grid.io.local.LocalFileInputStream.<init>(LocalFileInputStream.java:139)
        at edu.sdsc.grid.io.FileFactory.newFileInputStream(FileFactory.java:630)
```

**Comment by jrgriffiniii** [comment]
This was resolved by manually updating the owning user:

```bash
$ sudo chown -R dspace:dspace /mnt/disks/dataspaceproddatastore/prod-copy/assetstore_production/13/
```
