### ISSUE TITLE
OAR: Incorrect Page Highlighting 

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/dspace-development#620]
## Due Dates

**Proposed Due Date:** Flexible due date of 4/22.

Reason: This is not needed right away, but we don't want to put it off indefinitely.

**Adjusted Due Date:**

Reason:

## Description:

Please refer to the attached image. (see: red circled area at top)

Incorrectly highlighted “About” Tab on the web pages, including home page and Contact page. On the OAR homepage, “Home” tab should be highlighted instead of “About” and on the “Contact” page, “Contact” tab should be highlighted, not “About” tab.

## Acceptance Criteria:

- [ ] The highlighted page name will correlate with the active page 

![image (3)](https://user-images.githubusercontent.com/50670293/159940202-984b617c-29a0-40aa-8d65-c2b2ae92acc9.png)

**Comment by jrgriffiniii** [comment]
With introduces the changes tracked within , the following commands were needed: https://github.com/PrincetonUniversityLibrary/princeton-5/tree/oar-DEV-jspui-page-highlight

```bash
$ mvn dependency:purge-local-repository
$ mvn verify --fail-never
```

**Comment by jrgriffiniii** [comment]
Further diagnosis for deployment errors were found to be triggered by a missing `dev.properties` file. Unfortunately, now the following errors are found following deployment:

```bash
Apr 19, 2022 9:40:04 AM org.apache.catalina.core.ApplicationDispatcher invoke
SEVERE: Servlet.service() for servlet [jsp] threw exception
org.apache.jasper.JasperException: Unable to compile class for JSP:
An error occurred at line: [121] in the jsp file: [/layout/header-default.jsp]
params.currentUser cannot be resolved to a type
118:     <%
119:         if (analyticsKey != null && analyticsKey.length() > 0) {
120:             out.println("<!-- google analytics javascript snippet for '" + analyticsKey + "' -->");
121:             if (null != params.currentUser) {
122:                 out.println("<!-- not tracking analytics when logged in  -->");
123:             } else {
124:                 if (params.isTestInstance()) {


An error occurred at line: [124] in the jsp file: [/layout/header-default.jsp]
params cannot be resolved
121:             if (null != params.currentUser) {
122:                 out.println("<!-- not tracking analytics when logged in  -->");
123:             } else {
124:                 if (params.isTestInstance()) {
125:                     out.println("<!-- tracking analytics in production only  -->");
126:                 } else {
127:     %>


Stacktrace:
        at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:103)
        at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:392)
        at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:594)
```

**Comment by jrgriffiniii** [comment]
Various updates were required for the file `dspace-jspui/src/main/webapp/layout/header-default.jsp` (please see https://github.com/PrincetonUniversityLibrary/princeton-5/compare/oar-client-DEV...oar-DEV-jspui-page-highlight#diff-2a91a1790d2c82f4759544847c40b1bea5e3981b4cd0e938b560a16d66524509)

I should now be in the position to proceed with debugging this.

**Comment by jrgriffiniii** [comment]
https://github.com/PrincetonUniversityLibrary/princeton-5/pull/4 proposes the changes needed for the `dev` environment.

**Comment by jrgriffiniii** [comment]
The following pull requests require review for this:

- https://github.com/PrincetonUniversityLibrary/princeton-5/pull/4
- https://github.com/PrincetonUniversityLibrary/princeton-5/pull/5
- https://github.com/PrincetonUniversityLibrary/princeton-5/pull/6
