### ISSUE TITLE
Import dissertations records for March through May 2022 into DataSpace

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dspace-development#637]
Per Lynn Durgin's email, import these dissertations into DataSpace by June 15.

ETDAdmin report for this batch - [ETDAdminReport.xlsx](https://github.com/pulibrary/dspace-development/files/8816117/ETDAdminReport.xlsx)

**Comment by bess** [comment]
Something crashed during import: 

```
14 submission_891097
Processing collections file: collections
Adding item from directory submission_891696
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.dspace.app.itemimport.ItemImport.addItem(ItemImport.java:865)
	at org.dspace.app.itemimport.ItemImport.addItems(ItemImport.java:736)
	at org.dspace.app.itemimport.ItemImport.main(ItemImport.java:498)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
	at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:78)
java.lang.ArrayIndexOutOfBoundsException: 0
Started: 1655142558018
Ended: 1655142575226
Elapsed time: 17 secs (17208 msecs)
```

Working on debugging it now.
