### ISSUE TITLE
oaworkflow.princeton.edu is inaccessible

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#644]
Please see the following:

![image](https://user-images.githubusercontent.com/1443986/173870198-7c656557-3ad4-4070-bf01-6a75ceb8eb5b.png)

**Comment by jrgriffiniii** [comment]
The server environment seems to have been restarted or crashed. The following stack trace is now logged when attempting to restart the application:

```
Log entry ID: 382bde38-8ee6-4111-b7fe-aecc34aad135
Logged at: 13:17:40.379 15/06/22

Level 1:
-------
Exception type: Symplectic.Elements.DataEntities.WebsiteServerErrorException
Message: The website encountered a problem while handling a webpage request.
Exception not yet thrown.

Level 2:
-------
Exception type: System.Collections.Generic.KeyNotFoundException
Message: The given key was not present in the dictionary.
Stack trace:
at System.Collections.Generic.Dictionary<TKey, TValue>.get_Item(TKey)
at Symplectic.Elements.DataEntities.ObjectModel.UserCache..ctor(Int64, RMBasicUserData, Dictionary<Int32, RMUserMessageOptions>, List<RMBasicUserData>, List<RMDelegate>, Dictionary<Int32, Group>, Dictionary<Int32, HerdcGroup>, List<RMUserRoleMapEntry>, List<RMGroupRoleMapEntry>, ICache) in elements\DataEntities\ObjectModel\RightsModel.cs:line 1158, char 24
at Symplectic.Elements.DataAccess.ElementsDatabase.GetUserCache() in elements\DataAccess\ElementsDatabase.cs:line 2115, char 5
at Symplectic.Elements.DataAccess.CacheManager.get_UserCache() in elements\DataAccess\CacheManager.cs:line 95, char 7
at Symplectic.Elements.DataEntities.Caching.Cache.get_TheUserCache() in elements\DataEntities\Caching\Cache.cs:line 218, char 5
at Symplectic.Elements.Website.Application.UISerialise.StandardConfiguration(RMUser) in elements\Website.Application\UISerialise.cs:line 53, char 4
at Symplectic.Elements.Website.Application.BaseHandlers.XmlOutputHandler<T>.SerialiseStandard(SafeXmlTextWriter, Boolean) in elements\Website.Application\BaseHandlers\XmlOutputHandler.cs:line 274, char 4
at Symplectic.Elements.Website.Application.Handlers.LoginPage.Respond(LoginProgress) in elements\Website.Application\Handlers\Login.cs:line 532, char 4
at Symplectic.Elements.Website.Application.Handlers.LoginPage.WriteOutputData() in elements\Website.Application\Handlers\Login.cs:line 328, char 5
at Symplectic.Elements.Website.Application.BaseHandlers.XmlOutputHandler<T>.InnerProcessRequest() in elements\Website.Application\BaseHandlers\XmlOutputHandler.cs:line 124, char 5



2022-06-15 13:17:40: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Symplectic.Elements.DataEntities.ObjectModel.UserCache..ctor(Int64 cacheID, RMBasicUserData systemUser, Dictionary`2 messageOptions, List`1 allUsers, List`1 delegates, Dictionary`2 groups, Dictionary`2 herdcGroups, List`1 userRoles, List`1 groupRoles, ICache cache) in C:\BuildAgent\work\2f923cdb0b81569d\elements\DataEntities\ObjectModel\RightsModel.cs:line 1158
   at Symplectic.Elements.DataAccess.ElementsDatabase.GetUserCache() in C:\BuildAgent\work\2f923cdb0b81569d\elements\DataAccess\ElementsDatabase.cs:line 2115
   at Symplectic.Elements.DataAccess.CacheManager.get_UserCache() in C:\BuildAgent\work\2f923cdb0b81569d\elements\DataAccess\CacheManager.cs:line 95
   at Symplectic.Elements.DataEntities.Caching.Cache.get_TheUserCache() in C:\BuildAgent\work\2f923cdb0b81569d\elements\DataEntities\Caching\Cache.cs:line 218
   at Symplectic.Elements.Website.Application.UISerialise.StandardConfiguration(RMUser impersonatedUser) in C:\BuildAgent\work\2f923cdb0b81569d\elements\Website.Application\UISerialise.cs:line 53
   at Symplectic.Elements.Website.Application.BaseHandlers.XmlOutputHandler`1.SerialiseStandard(SafeXmlTextWriter page, Boolean includeMenu) in C:\BuildAgent\work\2f923cdb0b81569d\elements\Website.Application\BaseHandlers\XmlOutputHandler.cs:line 274
   at Symplectic.Elements.Website.Application.BaseHandlers.XmlOutputHandler`1.HandleResponseException(Exception doh) in C:\BuildAgent\work\2f923cdb0b81569d\elements\Website.Application\BaseHandlers\XmlOutputHandler.cs:line 517
2022-06-15 13:17:40: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
```

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/dspace-development/issues/558 documents the same error.

**Comment by jrgriffiniii** [comment]
Applying the same solution (https://gist.github.com/jrgriffiniii/8b4543ec7d0d0584f5b8455c907e2a09) resolved this issue once again.
