### ISSUE TITLE
Princeton to test Repository Connections

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#659]

**Comment by jrgriffiniii** [comment]
This is blocked by the discovery that the API endpoints cannot be accessed for the DEV environment, however, these were working previously. I have requested support for this from the Digital Science team (please see https://3.basecamp.com/3804430/buckets/26643531/todos/4720742011#__recording_5175252796).

**Comment by jrgriffiniii** [comment]
I will need to ensure that `oar-staging.princeton.edu/rt4ds` is able to be configured and interface with the migrated production endpoint https://princeton.elements.symplectic.org/api.html

**Comment by jrgriffiniii** [comment]
I am still experiencing difficulties troubleshooting the deployment of `rt4ds` with the following error:

```bash
INFO: validateJarFile(/mnt/disks/oarstagingdatastore/prod-copy/dspace/webapps.static/rt4ds/WEB-INF/lib/servlet-api-2.5.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class
```

**Comment by jrgriffiniii** [comment]
Referencing the specification, I find the following:

> # 10.7.2 Web Application Class Loader
> The class loader that a container uses to load a servlet in a WAR must allow the developer to load any resources contained in library JARs within the WAR following normal Java SE semantics using getResource. As described in the Java EE license agreement, servlet containers that are not part of a Java EE product should not allow the application to override Java SE platform classes, such as those in the java.* and javax.* namespaces, that Java SE does not allow to be modified. The container should not allow applications to override or access the container’s implementation classes. It is recommended also that the application class loader be implemented so that classes and resources packaged within the WAR are loaded in preference to
classes and resources residing in container-wide library JARs. An implementation MUST also guarantee that for every web application deployed in a container, a call to Thread.currentThread.getContextClassLoader() MUST return a ClassLoader instance that implements the contract specified in this section. Furthermore, the ClassLoader instance MUST be a separate instance for each deployed web application. The container is required to set the thread context ClassLoader as described above before making any callbacks (including listener
callbacks) into the web application, and set it back to the original ClassLoader, once the callback returns.
```

**Comment by jrgriffiniii** [comment]
Removing a redundant JAR dependency within the `staging` environment (`servlet-api-2.5.jar`) seems to have assisted in resolving this, however, the  `rt4ds` endpoint still seems to fail to deploy:

```bash
INFO: Deploying deployment descriptor [/home/dspace/apache-tomcat-7.0.104/conf/Catalina/localhost/rt4ds.xml]
Jul 29, 2022 11:44:40 AM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://java.sun.com/jstl/fmt is already defined
Jul 29, 2022 11:44:41 AM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://java.sun.com/jstl/fmt is already defined
Jul 29, 2022 11:44:41 AM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Jul 29, 2022 11:44:45 AM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deployment of deployment descriptor [/home/dspace/apache-tomcat-7.0.104/conf/Catalina/localhost/rt4ds.xml] has finished in [5,772] ms
```

Please note that these warnings are also present for other servlet applications which are being redeployed successfully.

**Comment by jrgriffiniii** [comment]
Redeploying this once again seems to have restored the `rt4ds` endpoint:

```bash
dspace@gcp-oar-staging1:~$ curl -v http://localhost:8080/rt4ds/repository
Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /rt4ds/repository HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< Content-Type: application/atom+xml; type=feed;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Fri, 29 Jul 2022 16:15:54 GMT
<
{ [44828 bytes data]
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>List Holdings</title>
  <link rel="self" href="https://oar.princeton.edu/rt4ds/repository" />
```

**Comment by jrgriffiniii** [comment]
The following errors are raised from the Elements deployment:

```bash
Technical details:
Exception on machine: NetBIOS name "PRINCE-2EON1", OS "Microsoft Windows NT 6.2.9200.0" (64-bit)
Software instance: elements-prince-prod, Software Version: 6.7.0.3384 (hosted), Commit Hash: c03a72e200ac711d11d92119d8d7b3045d98ef4e
Command ""S:\Symplectic\Elements\elements-prince-prod\Api.Host\Api.Host.exe"" (32-bit)
--------------------------------------------------------------------------------------
Log entry ID: fb971389-916c-4905-8f5e-b903037a2532
Logged at: 14:35:02.057 29/07/22

Level 1:
-------
Exception type: System.ServiceModel.AddressAccessDeniedException
Message: HTTP could not register URL http://+:9090/publications-atom/. Your process does not have access rights to this namespace (see http://go.microsoft.com/fwlink/?LinkId=70353 for details).
Stack trace:
at System.ServiceModel.Channels.SharedHttpTransportManager.OnOpen()
at System.ServiceModel.Channels.TransportManager.Open(TransportChannelListener)
at System.ServiceModel.Channels.TransportManagerContainer.Open(SelectTransportManagersCallback)
at System.ServiceModel.Channels.TransportChannelListener.OnOpen(TimeSpan)
at System.ServiceModel.Channels.HttpChannelListener<TChannel>.OnOpen(TimeSpan)
at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan)
at System.ServiceModel.Dispatcher.ChannelDispatcher.OnOpen(TimeSpan)
at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan)
at System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan)
at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan)
at Symplectic.Elements.Api.Host.Program.Main(String[]) in elements\Api.Host\Program.cs:line 89, char 7
Level 2:
-------
Exception type: System.Net.HttpListenerException
Message: Access is denied
Stack trace:
at System.Net.HttpListener.AddAllPrefixes()
at System.Net.HttpListener.Start()
at System.ServiceModel.Channels.SharedHttpTransportManager.OnOpen()
```

**Comment by jrgriffiniii** [comment]
`oar-staging` without Elements integration was breaking for Item submissions (due to a configuration error for the test ARK generation). This has now been fixed and tested with https://oar-staging.princeton.edu/handle/99999/fk4bs0b28g

**Comment by jrgriffiniii** [comment]
The following error seems to repeated every 5 minutes for the Elements production deployment. I am uncertain as to whether or not this may be related as to why the synchronization is not behaving as expected, but I have requested assistance from Digital Science in response to this:

```
Technical details:
Exception on machine: NetBIOS name "PRINCE-2EON1", OS "Microsoft Windows NT 6.2.9200.0" (64-bit)
Software instance: elements-prince-prod, Software Version: 6.7.0.3384 (hosted), Commit Hash: c03a72e200ac711d11d92119d8d7b3045d98ef4e
Command ""S:\Symplectic\Elements\elements-prince-prod\Api.Host\Api.Host.exe"" (32-bit)
--------------------------------------------------------------------------------------
Log entry ID: 7e088365-4401-401c-8cff-aca5e35f6708
Logged at: 15:58:31.853 29/07/22

Level 1:
-------
Exception type: System.ServiceModel.AddressAccessDeniedException
Message: HTTP could not register URL http://+:9090/publications-atom/. Your process does not have access rights to this namespace (see http://go.microsoft.com/fwlink/?LinkId=70353 for details).
Stack trace:
at System.ServiceModel.Channels.SharedHttpTransportManager.OnOpen()
at System.ServiceModel.Channels.TransportManager.Open(TransportChannelListener)
at System.ServiceModel.Channels.TransportManagerContainer.Open(SelectTransportManagersCallback)
at System.ServiceModel.Channels.TransportChannelListener.OnOpen(TimeSpan)
at System.ServiceModel.Channels.HttpChannelListener<TChannel>.OnOpen(TimeSpan)
at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan)
at System.ServiceModel.Dispatcher.ChannelDispatcher.OnOpen(TimeSpan)
at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan)
at System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan)
at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan)
at Symplectic.Elements.Api.Host.Program.Main(String[]) in elements\Api.Host\Program.cs:line 89, char 7
Level 2:
-------
Exception type: System.Net.HttpListenerException
Message: Access is denied
Stack trace:
at System.Net.HttpListener.AddAllPrefixes()
at System.Net.HttpListener.Start()
at System.ServiceModel.Channels.SharedHttpTransportManager.OnOpen()
```

**Comment by jrgriffiniii** [comment]
This has been successfully tested for deposits from the production Elements environment:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/c04fc492-7846-4a70-90ad-4ecea80630c6)

**Comment by jrgriffiniii** [comment]
There still appear to be network connectivity problems, and these now seem to affect both the `production` and `dev` environments:

```
$ date                                                                                                                 
Mon Aug 15 11:21:23 EDT 2022
$ curl -v https://princeton.elements.symplectic.org:8091/secure-api/v5.5
*   Trying 147.135.6.233...
* TCP_NODELAY set
^C
$ date                                                                                                                
Mon Aug 15 11:21:33 EDT 2022
$ curl https://checkip.amazonaws.com
137.83.217.149
```

**Comment by jrgriffiniii** [comment]
I have attempted to further diagnose this, but could not resolve this without assistance. Please note that I have requested further assistance from the Digital Science migration team:

https://3.basecamp.com/3804430/buckets/26643531/todos/4720742011#__recording_5229383727

**Comment by jrgriffiniii** [comment]
The API endpoints for the `production` and `dev` are now accessible following firewall adjustments for the server environments:

https://3.basecamp.com/3804430/buckets/26643531/todos/4720742011#__recording_5250752569
