### ISSUE TITLE
dataspace-dev cannot mint arks

### ISSUE THREAD

**Issue by bess** [pulibrary/dspace-development#671]
I cannot create a collection on dataspace-dev. Is this because it is set up to use the EZID test sever? Or is this because we need to apply the fix we applied in production (the 200 OK vs 201 CREATED fix)? 

```
Date: Tue, 16 Aug 2022 09:44:33 -0400 (EDT)
From: dspadmin@princeton.edu
To: dspadmin@princeton.edu
Subject: DataSpace: Internal Server Error


An internal server error occurred on https://dataspace-dev.princeton.edu:

Date:       8/16/22 9:44 AM
Session ID: 277945274958D89E31186F777231D85B
User:       Bess Sadler (bess.sadler@princeton.edu)
IP address: 10.0.20.7

-- URL Was: https://dataspace-dev.princeton.edu/tools/collection-wizard
-- Method: POST
-- Parameters were:
-- community_id: "267"


Exception:
java.lang.RuntimeException: ARK not created:  OK:  ark:/99999/fk4c83v65g
	at org.dspace.handle.HandleManager.createHandle(HandleManager.java:197)
	at org.dspace.content.Collection.create(Collection.java:236)
	at org.dspace.content.Community.createCollection(Community.java:934)
	at org.dspace.content.Community.createCollection(Community.java:918)
```

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/dspace-development/671?planning-poker) with ZenHub @hectorcorrea @jrgriffiniii @bess

**Comment by jrgriffiniii** [comment]
Given the discussion in https://github.com/PrincetonUniversityLibrary/princeton-5/pull/40#issuecomment-1308848920, I am going to consider this resolved.
