### ISSUE TITLE
Item uploads fail in the Symplectic Elements production environment (oaworkflow.princeton.edu)

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#69]
The following error was encountered by a student worker using Symplectic Elements:

![thumbnail_error_message](https://user-images.githubusercontent.com/1443986/87254258-435f4900-c44f-11ea-8980-6f590f6684be.png)

**Comment by jrgriffiniii** [comment]
I was able to reproduce this with the following upload attempt, as when I attempted to create an item with a sample PDF file:

![image](https://user-images.githubusercontent.com/1443986/87254585-93d7a600-c451-11ea-88db-7bb5550e0b56.png)

...the following error message was created:

![image](https://user-images.githubusercontent.com/1443986/87254606-b79aec00-c451-11ea-87b0-c2bf793aef8c.png)

**Comment by jrgriffiniii** [comment]
The following error was logged for the repository connector:

```
Exception type: System.Web.Http.HttpResponseException
Message: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
Stack trace:
at Symplectic.Foundation.Http.SympHttpClient+<SendAsync>d__16.MoveNext() in libraries\Symplectic.Foundation\Http\SympHttpClient.cs:line 364, char 6
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task)
at Symplectic.Foundation.Http.SympHttpClient+<GetBufferedResponseAsync>d__13.MoveNext() in libraries\Symplectic.Foundation\Http\SympHttpClient.cs:line 266, char 10
at Symplectic.Foundation.Concurrency.AggregateExceptionHandling.RethrowFirstInnerNonAggregateExeption(AggregateException) in libraries\Symplectic.Foundation\Concurrency\AggregateExceptionHandling.cs:line 25, char 4
at Symplectic.Foundation.Concurrency.AggregateExceptionHandling.UnwrapResultingAggregateExceptions<TResult>(Func<TResult>) in libraries\Symplectic.Foundation\Concurrency\AggregateExceptionHandling.cs:line 40, char 5
at Symplectic.Foundation.Http.SympHttpClient.GetBufferedResponse(HttpRequestMessage, Nullable<TimeSpan>) in libraries\Symplectic.Foundation\Http\SympHttpClient.cs:line 244, char 4
at Symplectic.Elements.Repository.Client.Rt1RepositoryClient.UploadFile(ApiRepositoryPublication, Rt1RepositoryFileType, MonitoringStreamCopier, String, String, String, Int64) in elements\Repository.Client\Rt1RepositoryClient.cs:line 519, char 5

HttpResponseException-specific information:
	Request Method: POST
	Request URL: https://oar.princeton.edu/rt4ds/repository
	Response Status Code: 500
	Response Reason Phrase: Internal Server Error
```

**Comment by jrgriffiniii** [comment]
This is a file-system level permissions error on oar.princeton.edu:

```
Caused by: org.apache.commons.fileupload.FileUploadBase$IOFileUploadException: Processing of multipart/form-data request failed. /var/cache/tomcat/temp/upload_2a455bfe_1734466efa8__7fff_00000002.tmp (Permission denied)
        at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:367)
        at org.apache.commons.fileupload.servlet.ServletFileUpload.parseRequest(ServletFileUpload.java:126)
        at uk.co.symplectic.elements.servlets.RepositoryServlet.getFilesFromRequest(RepositoryServlet.java:324)
        ... 27 more
Caused by: java.io.FileNotFoundException: /var/cache/tomcat/temp/upload_2a455bfe_1734466efa8__7fff_00000002.tmp (Permission denied)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
        at org.apache.commons.io.output.DeferredFileOutputStream.thresholdReached(DeferredFileOutputStream.java:178)
        at org.apache.commons.io.output.ThresholdingOutputStream.checkThreshold(ThresholdingOutputStream.java:224)
        at org.apache.commons.io.output.ThresholdingOutputStream.write(ThresholdingOutputStream.java:128)
        at org.apache.commons.fileupload.util.Streams.copy(Streams.java:101)
        at org.apache.commons.fileupload.util.Streams.copy(Streams.java:64)
        at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:362)
```

I am not certain what triggered this change in file-system permissions for the referenced directory.

**Comment by jrgriffiniii** [comment]
This should be functioning, however I am encountering issues when I attempt to submit a file using my personal account (which does not have a Department linking it to an OAR Collection):

```
2020-07-12 15:55:35,496 DEBUG org.dspace.storage.rdbms.DatabaseManager @ Running query "SELECT * FROM symplectic_pids WHERE pid = ?"  with parameters: 209596
2020-07-12 15:55:35,496 DEBUG org.dspace.storage.rdbms.DatabaseManager @ Running query "SELECT * FROM symplectic_coll_map WHERE key_text = ?"  with parameters: /Organisation
2020-07-12 15:55:35,498 DEBUG org.dspace.storage.rdbms.DatabaseManager @ Running query "SELECT * FROM symplectic_coll_def"  with parameters:
2020-07-12 15:55:35,499 INFO  uk.co.symplectic.publications.process.SynchroniseLock @ Unlocking 209596
2020-07-12 15:55:35,499 INFO  uk.co.symplectic.publications.process.SynchroniseLock @ Unlocking 209596
2020-07-12 15:55:35,500 ERROR uk.co.symplectic.elements.servlets.RepositoryServlet @ Caught ElementsException
uk.co.symplectic.elements.ElementsException: uk.co.symplectic.repository.dspace.DSpaceElementsException: No collection mappings found, and no default collections set
        at uk.co.symplectic.repository.dspace.DSpaceItemManager.getDepositRepresentation(DSpaceItemManager.java:171)
```

**Comment by jrgriffiniii** [comment]
Given that this should not affect other users, I have requested that this feature be tested by the user who reported this bug.
