### ISSUE TITLE
The DataSpace embargo lift report has raised errors when attempting to generate the report for 02/27/23

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#734]
Please see the following error report:

> Feb 27, 2023 8:00:16 AM org.postgresql.core.v3.ConnectionFactoryImpl log
WARNING: IOException occurred while connecting to 10.64.16.3:5432
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at org.postgresql.core.PGStream.<init>(PGStream.java:69)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:158)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:452)
        at org.postgresql.Driver.connect(Driver.java:254)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:75)
        at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
        at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:974)
        at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
        at org.dspace.storage.rdbms.DataSourceInit.getDatasource(DataSourceInit.java:140)
        at org.dspace.storage.rdbms.DatabaseManager.initDataSource(DatabaseManager.java:1440)
        at org.dspace.storage.rdbms.DatabaseManager.initialize(DatabaseManager.java:1333)
        at org.dspace.storage.rdbms.DatabaseManager.getDataSource(DatabaseManager.java:650)
        at org.dspace.storage.rdbms.DatabaseManager.getConnection(DatabaseManager.java:629)
        at org.dspace.core.Context.init(Context.java:121)
        at org.dspace.core.Context.<init>(Context.java:95)
        at org.dspace.embargo.EmbargoManager.main(EmbargoManager.java:268)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
        at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:78)

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/dataspace_embargo_lifter is the precise project where this is failure is originating.

**Comment by jrgriffiniii** [comment]
Depending upon whether or not this error is raised tomorrow (02/28/23), this may simply be an anomaly (due to network connectivity issues) and closed.

**Comment by jrgriffiniii** [comment]
This was indeed triggered by an anomalous connection issue for PostgreSQL.
