### ISSUE TITLE
Indexing is failing for the imported DataSpace dissertations

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#75]
As reported by a user:

```
Regarding the June 2020s, it doesn’t appear that they are indexing—for example no items appear under the Issue Date browse for 2020 https://dataspace.princeton.edu/jspui/handle/88435/dsp01td96k251d/browse?type=dateissued&submit_browse=Issue+Date.

Also, if I search for one of the student’s names from this batch “Silpe” it does not come up as a search result. https://dataspace.princeton.edu/jspui/simple-search?query=silpe&location=88435%2Fdsp01kp78gg38w
```

**Comment by jrgriffiniii** [comment]
Indexing is failing using the following JRuby commands:

```
java_import org.dspace.discovery.SolrServiceImpl
index_service = DSpace.getIndexService
item = DSpace.fromString(handle)
index_service = DSpace.getIndexService
index_service.indexContent(DSpace.context, item, true)
index_service.getSolr.commit
```

**Comment by jrgriffiniii** [comment]
There is a file-system level permissions issue which is triggering Solr from indexing:
```
Caused by: java.io.FileNotFoundException: /var/cache/tomcat/temp/upload__7e9a8c0d_1735399fe3c__7fff_00042421.tmp (Permission denied)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
        at org.apache.commons.io.output.DeferredFileOutputStream.thresholdReached(DeferredFileOutputStream.java:178)
        at org.apache.commons.io.output.ThresholdingOutputStream.checkThreshold(ThresholdingOutputStream.java:224)
        at org.apache.commons.io.output.ThresholdingOutputStream.write(ThresholdingOutputStream.java:128)
        at org.apache.commons.fileupload.util.Streams.copy(Streams.java:101)
        at org.apache.commons.fileupload.util.Streams.copy(Streams.java:64)
        at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:362)
```

**Comment by jrgriffiniii** [comment]
Manually committing the document update with:

```
index_service.getSolr.commit
```

was necessary, but the Solr indexing is now functioning.

**Comment by jrgriffiniii** [comment]
The index has been updated for the September 2019 dissertation imports.

**Comment by jrgriffiniii** [comment]
The index has been updated for the June 2020 dissertation imports.
