### ISSUE TITLE
[oar] Test and Troubleshoot the OAI-PMH Endpoint

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#804]
Currently, the OAI-PMH endpoint is not actively enabled and functioning for the OAR. If possible, this should be online and accessible by the public (as is the case for DataSpace with https://dataspace.princeton.edu/oai).

**Comment by jrgriffiniii** [comment]
I have found where the OAI is failing, and I believe that this can be remedied by ensuring that the proper JAR dependency is found by the Tomcat servlet engine:

```bash
SEVERE: Error configuring application listener of class [org.dspace.servicemanager.servlet.DSpaceKernelServletContextListener]
java.lang.ClassNotFoundException: org.dspace.servicemanager.servlet.DSpaceKernelServletContextListener
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1952)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1795)
        at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:535)
        at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:517)
        at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:148)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5048)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5653)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1007)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:983)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:639)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1296)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2037)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

Jan 22, 2024 2:40:43 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Error configuring application listener of class [org.dspace.app.util.DSpaceContextListener]
java.lang.ClassNotFoundException: org.dspace.app.util.DSpaceContextListener
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1952)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1795)
        at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:535)
        at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:517)
        at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:148)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5048)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5653)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1007)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:983)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:639)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1296)
```

**Comment by jrgriffiniii** [comment]
I apologize for the delays with this, the `oai` endpoint has now been successfully deployed within the `dev` environment:
<img width="1269" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenoyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--253c26e9dcfd458222cc76e67538b8d44efd450c/image.png" alt="image.png" />

**Comment by jrgriffiniii** [comment]
The following JARs needed to be included within the `CLASSPATH` for the `oai` servlet:

```bash
-rw-rw-r-- 1 dspace dspace  581571 Jan 24 10:22 joda-time-2.3.jar
-rw-rw-r-- 1 dspace dspace   38583 Jan 24 10:21 oai4j-0.6b1.jar
-rw-rw-r-- 1 dspace dspace   19827 Jan 24 10:20 opencsv-2.3.jar
-rw-rw-r-- 1 dspace dspace   64849 Jan 24 10:18 jbibtex-1.0.10.jar
-rw-rw-r-- 1 dspace dspace   34456 Jan 24 10:17 bte-io-0.9.3.5.jar
-rw-rw-r-- 1 dspace dspace   23341 Jan 24 10:16 bte-core-0.9.3.5.jar
-rw-rw-r-- 1 dspace dspace  388864 Jan 24 10:15 mail-1.4.jar
-rw-rw-r-- 1 dspace dspace    2497 Jan 24 10:13 javax.inject-1.jar
-rw-rw-r-- 1 dspace dspace  271237 Jan 24 10:12 ehcache-core-1.7.2.jar
-rw-rw-r-- 1 dspace dspace  252567 Jan 24 10:10 flyway-core-3.0.jar
-rw-rw-r-- 1 dspace dspace  794639 Jan 24 10:09 postgresql-42.2.1.jar
-rw-rw-r-- 1 dspace dspace  160519 Jan 24 10:08 commons-dbcp-1.4.jar
-rw-rw-r-- 1 dspace dspace   87077 Jan 24 10:07 commons-pool-1.4.jar
-rw-rw-r-- 1 dspace dspace  315805 Jan 24 10:05 commons-lang3-3.1.jar
-rw-rw-r-- 1 dspace dspace  284220 Jan 24 10:05 commons-lang-2.6.jar
-rw-rw-r-- 1 dspace dspace  129875 Jan 24 10:02 dspace-services-5.5-SNAPSHOT.jar
-rw-rw-r-- 1 dspace dspace  849980 Jan 24 10:01 dspace-api-lang-5.0.7.jar
-rw-rw-r-- 1 dspace dspace 2236951 Jan 24 10:01 dspace-api-5.5-SNAPSHOT.jar
-rw-rw-r-- 1 dspace dspace  128999 Jan 23 14:16 dspace-oai-5.5-SNAPSHOT-classes.jar
```

**Comment by jrgriffiniii** [comment]
The `oai` endpoint has now been successfully deployed to the `staging` environment:
<img width="1274" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXIyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00cb469ba7ebc7e56c6f553cf6996853d0da39ce/image.png" alt="image.png" />

**Comment by jrgriffiniii** [comment]
This is awaiting deployment into the `production` environment tomorrow, after which it shall be submitted for review for end-users.

**Comment by kelynch** [comment]
I reviewed https://oar-staging.princeton.edu/oai with @hhkitsune and confirmed it looks good.  This is ready to be deployed any time over the next couple of weeks before 2:00PM EST to minimize disruption to OAR users.

**Comment by jrgriffiniii** [comment]
This has been successfully released into the `production` environment:
![image](https://github.com/pulibrary/dspace-development/assets/1443986/9264273b-9af3-40c3-acc6-762c3d0db547)

**Comment by jrgriffiniii** [comment]
Please note that it was necessary to recopy the JAR dependencies after multiple attempts to restart the `tomcat` service. Further, the following needed to be explicitly copied:
```bash
$ cp /dspace/webapps/rest/WEB-INF/lib/joda-time-2.3.jar /dspace/webapps/oai/WEB-INF/lib/
```
