### ISSUE TITLE
[dataspace] DataSpace Bitstream requests are resulting in `java.lang.NullPointerException`

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#815]
The following errors are being captured and logged for `libanswers`. These number in more than 700 errors, and these do not refer to the same PDF Bitstream:

```
Date: 4/10/24 5:27 AM
Session ID: [SESSION_ID]
User: Anonymous
IP address: [IP]

-- URL Was: https://dataspace.princeton.edu/bitstream/88435/dsp01wd375w30d/1/473.pdf
-- Method: GET
-- Parameters were:


Exception:
java.lang.NullPointerException
at org.dspace.app.webui.servlet.BitstreamServlet.doDSGet(BitstreamServlet.java:78)
at org.dspace.app.webui.servlet.DSpaceServlet.processRequest(DSpaceServlet.java:130)
at org.dspace.app.webui.servlet.DSpaceServlet.doGet(DSpaceServlet.java:75)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.dspace.utils.servlet.DSpaceWebappServletFilter.doFilter(DSpaceWebappServletFilter.java:78)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:165)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654)
at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:317)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:750)

```

**Comment by jrgriffiniii** [comment]
This is still occurring, and I must review the code base and database in order to understand why this is failing:

```bash
java.lang.NullPointerException
        at org.dspace.app.webui.servlet.BitstreamServlet.doDSGet(BitstreamServlet.java:78)
        at org.dspace.app.webui.servlet.DSpaceServlet.processRequest(DSpaceServlet.java:130)
        at org.dspace.app.webui.servlet.DSpaceServlet.doGet(DSpaceServlet.java:75)                                                                                            at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)                                                                  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)                                                                  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.dspace.utils.servlet.DSpaceWebappServletFilter.doFilter(DSpaceWebappServletFilter.java:78)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)                                                                  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)                                                                                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:165)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)                                                                                      at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)                                                                                        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:317)                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)                                                                                 at java.lang.Thread.run(Thread.java:750
```

**Comment by jrgriffiniii** [comment]
There are some cases in which other errors are raised:

<img width="865" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenBoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0602b9fa7007fb0dfaed801e16bc308a3bb06f58/image.png" alt="image.png" />

**Comment by jrgriffiniii** [comment]
This might be related to the name of the PDF file:
```bash
2024-04-16 12:33:21,289 ERROR org.dspace.app.webui.servlet.BitstreamServlet @ anonymous:session_id=717805F5EF35A9F78788C8D1F82C7F5D:ip_addr=68.33.92.251:view_bitstrea
m:Error parsing the sequence ID\colon; WomenLeaders_2010.pdf
2024-04-16 12:33:21,291 ERROR org.dspace.app.webui.servlet.DSpaceServlet @ anonymous:session_id=717805F5EF35A9F78788C8D1F82C7F5D:ip_addr=68.33.92.251:unhandled error:
java.lang.NullPointerException
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
```

**Comment by jrgriffiniii** [comment]
Unfortunately, I have been struggling to reproduce the conditions which lead to this exact error. I am fairly certain that the afflicted Bitstream is this one: https://dataspace.princeton.edu/handle/88435/dsp01qr46r084n.
