### ISSUE TITLE
[thesis-central] Submissions fail for certain cases in which a RegExp substitution for e-mail subjects raises an error

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#825]
This error was reported by an end-user, and the following error seems to be the root cause:

```bash
Caused by: java.lang.IllegalArgumentException: Illegal group reference
        at java.util.regex.Matcher.appendReplacement(Matcher.java:808)
        at java.util.regex.Matcher.replaceAll(Matcher.java:906)
        at java.lang.String.replaceAll(String.java:2162)
        at org.tdl.vireo.services.StringVariableReplacement.applyParameterSubstitution(StringVariableReplacement.java:127)
        at org.tdl.vireo.email.impl.VireoEmailImpl.applyParameterSubstitution(VireoEmailImpl.java:292)
        at org.tdl.vireo.email.impl.EmailServiceImpl$EmailJob.doJob(EmailServiceImpl.java:115)
        ... 11 more
```

...which resolves to the following within the codebase:

```java
        @Override
        public void applyParameterSubstitution() {

                subject = StringVariableReplacement.applyParameterSubstitution(subject, parameters);
                message = StringVariableReplacement.applyParameterSubstitution(message, parameters);

        }
```

**Comment by jrgriffiniii** [comment]
The title was the following, containing characters which, unescaped for RegExp, would raise an exception: `Cheng-Yau Type Local Gradient Estimate for Harmonic Functions on $RCD^*(K,N)$ Metric Measure Spaces`

Replacing these characters, submitting the thesis, and then updating the title of the submitting thesis served as a solution for this.
