### ISSUE TITLE
Import a subset of 2020 Senior Theses and Doctoral Dissertations into the dataspace-dev for acceptance testing

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#99]
This needs to be addressed in order to ensure that end-users can test current interaction with DataSpace on the servers for the migrated DSpace custom implementations.

**Comment by jrgriffiniii** [comment]
The following submissions were successfully imported from the Chemistry department with the following Item IDs:

```
submission_8099 103417
submission_8129 103418
submission_8243 103419
submission_8254 103420
submission_8322 103421
submission_8359 103422
submission_8371 103423
submission_8546 103424
submission_8570 103425
submission_8657 103426
submission_8667 103427
submission_8698 103428
submission_8745 103429
submission_8868 103430
submission_9056 103431
submission_9118 103432
submission_9133 103433
submission_9251 103434
submission_9335 103435
submission_9433 103436
submission_9436 103437
submission_9445 103438
submission_9469 103439
```

**Comment by jrgriffiniii** [comment]
The following submissions were successfully imported from the Classics department with the following Item IDs:

```
submission_8323 103440
submission_8355 103441
submission_8544 103442
submission_8753 103443
submission_8816 103444
submission_9066 103445
submission_9182 103446
submission_9192 103447
submission_9334 103448
```

**Comment by jrgriffiniii** [comment]
The following submissions were successfully imported from the Physics department with the following Item IDs:

```
submission_8079 103449
submission_8106 103450
submission_8175 103451
submission_8211 103452
submission_8218 103453
submission_8256 103454
submission_8277 103455
submission_8283 103456
submission_8386 103457
submission_8392 103458
submission_8403 103459
submission_8439 103460
submission_8444 103461
submission_8474 103462
submission_8554 103463
submission_8563 103464
submission_8584 103465
submission_8650 103466
submission_8680 103467
submission_8739 103468
submission_8786 103469
submission_8823 103470
submission_8831 103471
submission_8844 103472
submission_8850 103473
submission_8928 103474
submission_8932 103475
submission_9020 103476
submission_9103 103477
submission_9105 103478
submission_9144 103479
submission_9153 103480
submission_9193 103481
submission_9211 103482
submission_9312 103483
submission_9316 103484
submission_9450 103485
submission_9480 103486
```

**Comment by jrgriffiniii** [comment]
Attempting to import doctoral dissertation batches yields the following errors:

```
java.lang.RuntimeException: Error while attempting to create identifier for Item id: 103490
	at org.dspace.identifier.HandleIdentifierProvider.register(HandleIdentifierProvider.java:82)
	at org.dspace.identifier.IdentifierServiceImpl.register(IdentifierServiceImpl.java:83)
	at org.dspace.content.InstallItem.installItem(InstallItem.java:70)
	at org.dspace.app.itemimport.ItemImport.addItem(ItemImport.java:916)
	at org.dspace.app.itemimport.ItemImport.addItems(ItemImport.java:736)
	at org.dspace.app.itemimport.ItemImport.main(ItemImport.java:498)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
	at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:78)
```

Unfortunately, I could not resolve the ARK-minting-related error, as the following did not seem to enable this functionality:

```
# These are configuration parameters for the EZID ARK minting service
  ark.ezid_server = https://ezid.cdlib.org
~ ark.ezid_username = apitest
~ ark.ezid_password = apitest
~ ark.shoulder = 99999/fk4
```

**Comment by jrgriffiniii** [comment]
The following configuration enabled the dissertations to be imported:

```
# We have hijacked the Handle Prefix to indicate our ARK naming assigning authority
  #  number (NAAN) instead.
~ handle.prefix = 99999

  # This plus the ARK identifier is stored as the persistent URI of the Item
  handle.canonical.prefix = http://arks.princeton.edu/ark:/

  # These are configuration parameters for the EZID ARK minting service
  ark.ezid_server = https://ezid.cdlib.org
~ ark.ezid_username = apitest
~ ark.ezid_password = apitest
~ ark.shoulder = fk4
```

**Comment by jrgriffiniii** [comment]
Dissertations from April 2020 were imported with the following Item IDs:

```
etdadmin_upload_709098 99999/fk4tf1528p
etdadmin_upload_713009 99999/fk4pp0f85g
etdadmin_upload_713285 99999/fk4jw9qg1h
etdadmin_upload_713325 99999/fk4f490n6q
etdadmin_upload_713402 99999/fk49c88v20
etdadmin_upload_713439 99999/fk45m7k19x
etdadmin_upload_713724 99999/fk41z5jm8r
etdadmin_upload_714218 99999/fk4x64v03q
etdadmin_upload_714626 99999/fk4sf44572
etdadmin_upload_714754 99999/fk4np3dc19
etdadmin_upload_714935 99999/fk4hx2pj6r
etdadmin_upload_715142 99999/fk4d51zr3w
etdadmin_upload_715339 99999/fk48d17z1m
etdadmin_upload_715359 99999/fk44q97j0n
etdadmin_upload_715396 99999/fk40z8hq8n
etdadmin_upload_715803 99999/fk4w67t323
etdadmin_upload_715864 99999/fk4rf7387z
etdadmin_upload_715877 99999/fk4mp6cg2q
etdadmin_upload_715931 99999/fk4gx5np01
etdadmin_upload_716055 99999/fk4c83n78t
etdadmin_upload_716064 99999/fk47h2xf5m
etdadmin_upload_716206 99999/fk43r26n2t
etdadmin_upload_716257 99999/fk4001gt84
etdadmin_upload_716463 99999/fk4v70s627
etdadmin_upload_716577 99999/fk4qg02c8m
etdadmin_upload_716600 99999/fk4kp9bk4n
etdadmin_upload_716808 99999/fk4g17b52r
etdadmin_upload_716877 99999/fk4b86mc02
etdadmin_upload_717040 99999/fk46h5wj61
etdadmin_upload_718234 99999/fk42r55q9v
etdadmin_upload_718828 99999/fk4z04g339
etdadmin_upload_718972 99999/fk4t73r898
etdadmin_upload_718988 99999/fk4pg31g6g
etdadmin_upload_719049 99999/fk4jt11268
etdadmin_upload_720521 99999/fk4f20983d
etdadmin_upload_720580 99999/fk4989kf94
etdadmin_upload_721046 99999/fk45h8vn4w
etdadmin_upload_721051 99999/fk41r84t9r
etdadmin_upload_722401 99999/fk4x07f64q
etdadmin_upload_722746 99999/fk4s76qd3j
```

**Comment by jrgriffiniii** [comment]
Reopening due to the fact that I did not document this process.

**Comment by jrgriffiniii** [comment]
For this process, I had built the SIPs using the `dspace-python` repository, with the objective of generating the SIPs in the .tgz (compressed TAR) format. I then tunneled to the server using the following:

```
ssh -L 1234:[DATASPACE_DEV]:22 pulsys@[BASTION_HOST]
```

Please note that, in order to support the copying of files over the SSH using `scp`, I needed to enable the following:

```
AllowTCPForwarding yes
```
within `/etc/ssh/sshd_config` on the server.

**Comment by jrgriffiniii** [comment]
My approach was to use `scp -P 1234 export/Chemistry/Chemistry.tgz pulsys@localhost:~/` in order to copy these files into the home directory of `pulsys`. I then simply decompressed these into the `/tmp` directory:

```
cd /tmp
mkdir /tmp/Chemistry
cd /tmp/Chemistry
tar xvf ~/Chemistry.tgz
```

I then changed users to `dspace`:

```
sudo su - dspace
```

And invoked a modified set of commands derived from the original `tcsh` script:

```
export EPERSON="jrg5@princeton.edu"
export COLLECTION_HANDLE="88435/dsp018c97kq479"
export DEPARTMENT="Chemistry"
/dspace/bin/dspace import --add --collection $COLLECTION_HANDLE --eperson $EPERSON --mapfile "import-$DEPARTMENT.map" --source "/tmp/$DEPARTMENT" --workflow
```

Following this, I then deleted the original `tgz`:

```

```

**Comment by jrgriffiniii** [comment]
# Doctoral Dissertations

This approach was similar to what was undertaken for the senior theses submissions, but much more manual and labor-intensive.

In order to retrieve the dissertations, one needed to SSH into the legacy DataSpace production server:

```
ssh -J [SERVICE_ACCOUNT]@[OIT_BASTION_HOST] [SERVICE_ACCOUNT]@dataspace.princeton.edu
sudo su - root
sudo su - dspace
cd dissertations/etd-ingest/sftp_upload
```

I then set a batch ID for the new set of dissertations:

```
export batch_id=20200408
```
...and create a new directory for importing these:

```
mkdir $batch_id
cd $batch_id
```

Unfortunately, at this point, the process is quite manual. I did not have the opportunity to script for this procedure:

```
sftp  dspace@[DSPACE_SFTP_HOST]
```

This will prompt one for the password. Please use the password stored in LastPass within `Shared-ITIMS-Passwords/dataspace/dataspace.princeton.edu`

One will then have the ability to search for the newly-uploaded .zip files:

```
-rw-r--r--    1 98041    pusvc    16255890 Nov 27  2019 etdadmin_upload_698620.zip
-rw-r--r--    1 98041    pusvc     1754092 Nov 27  2019 etdadmin_upload_701125.zip
-rw-r--r--    1 98041    pusvc    12005526 Nov 27  2019 etdadmin_upload_698417.zip
-rw-r--r--    1 98041    pusvc     2008759 Nov 27  2019 etdadmin_upload_698537.zip
-rw-r--r--    1 98041    pusvc    18973128 Nov 27  2019 etdadmin_upload_698097.zip
-rw-r--r--    1 98041    pusvc    20546463 Nov 27  2019 etdadmin_upload_698085.zip
-rw-r--r--    1 98041    pusvc     3124739 Nov 27  2019 etdadmin_upload_697535.zip
-rw-r--r--    1 98041    pusvc     9184066 Nov 27  2019 etdadmin_upload_698016.zip
-rw-r--r--    1 98041    pusvc     3248499 Nov 27  2019 etdadmin_upload_697355.zip
-rw-r--r--    1 98041    pusvc     9889669 Nov 27  2019 etdadmin_upload_697525.zip
-rw-r--r--    1 98041    pusvc    33621089 Nov 27  2019 etdadmin_upload_697167.zip
-rw-r--r--    1 98041    pusvc      952251 Nov 27  2019 etdadmin_upload_697183.zip
-rw-r--r--    1 98041    pusvc     9917007 Nov 27  2019 etdadmin_upload_697203.zip
-rw-r--r--    1 98041    pusvc     7065042 Nov 27  2019 etdadmin_upload_697029.zip
```

For the purposes of speed, I was simply manually selecting the files (or, downloading all files and sorting them after they had been copied over the SFTP to the DataSpace server environment).

**Comment by jrgriffiniii** [comment]
Following database updates applied by Atmire, the subset of senior theses and dissertations needed to be reimported.

The following submissions were successfully imported from the Chemistry department with the following Item IDs:

```
submission_8099 103453
submission_8129 103454
submission_8243 103455
submission_8254 103456
submission_8322 103457
submission_8359 103458
submission_8371 103459
submission_8546 103460
submission_8570 103461
submission_8657 103462
submission_8667 103463
submission_8698 103464
submission_8745 103465
submission_8868 103466
submission_9056 103467
submission_9118 103468
submission_9133 103469
submission_9251 103470
submission_9335 103471
submission_9433 103472
submission_9436 103473
submission_9445 103474
submission_9469 103475
```

The following submissions were successfully imported from the Classics department with the following Item IDs:

```
submission_8323 103476
submission_8355 103477
submission_8544 103478
submission_8753 103479
submission_8816 103480
submission_9066 103481
submission_9182 103482
submission_9192 103483
submission_9334 103484
```

The following submissions were successfully imported from the Physics department with the following Item IDs:

```
submission_8079 103485
submission_8106 103486
submission_8175 103487
submission_8211 103488
submission_8218 103489
submission_8256 103490
submission_8277 103491
submission_8283 103492
submission_8386 103493
submission_8392 103494
submission_8403 103495
submission_8439 103496
submission_8444 103497
submission_8474 103498
submission_8554 103499
submission_8563 103500
submission_8584 103501
submission_8650 103502
submission_8680 103503
submission_8739 103504
submission_8786 103505
submission_8823 103506
submission_8831 103507
submission_8844 103508
submission_8850 103509
submission_8928 103510
submission_8932 103511
submission_9020 103512
submission_9103 103513
submission_9105 103514
submission_9144 103515
submission_9153 103516
submission_9193 103517
submission_9211 103518
submission_9312 103519
submission_9316 103520
submission_9450 103521
submission_9480 103522
```

Dissertations from April 2020 were imported with the following ARKs:

```
etdadmin_upload_709098 99999/fk40s13z17
etdadmin_upload_713009 99999/fk4rb8cw5g
etdadmin_upload_713285 99999/fk4mk7p32q
etdadmin_upload_713325 99999/fk4gt6z875
etdadmin_upload_713402 99999/fk4c267g15
etdadmin_upload_713439 99999/fk4795hn6m
etdadmin_upload_713724 99999/fk43j4sv2w
etdadmin_upload_714218 99999/fk4zs4369n
etdadmin_upload_714626 99999/fk4v422s8t
etdadmin_upload_714754 99999/fk4qc1c06k
etdadmin_upload_714935 99999/fk4km0n62v
etdadmin_upload_715142 99999/fk4ft9xc6j
etdadmin_upload_715339 99999/fk4b296k12
etdadmin_upload_715359 99999/fk4698gr8j
etdadmin_upload_715396 99999/fk42j7rz5b
etdadmin_upload_715803 99999/fk4xw5rq20
etdadmin_upload_715864 99999/fk4t451w97
etdadmin_upload_715877 99999/fk4pc4b36g
etdadmin_upload_715931 99999/fk4jm3m92r
etdadmin_upload_716055 99999/fk4dv2wg76
etdadmin_upload_716064 99999/fk49325p37
etdadmin_upload_716206 99999/fk45b1fw01
etdadmin_upload_716257 99999/fk41n9ff87
etdadmin_upload_716463 99999/fk4ww8qt5f
etdadmin_upload_716577 99999/fk4s48109k
etdadmin_upload_716600 99999/fk4nc7963t
etdadmin_upload_716808 99999/fk4hm6kc88
etdadmin_upload_716877 99999/fk4cv5vk52
etdadmin_upload_717040 99999/fk48354s2m
etdadmin_upload_718234 99999/fk44f34c1w
etdadmin_upload_718828 99999/fk40p2dj8c
etdadmin_upload_718972 99999/fk4vx1px21
etdadmin_upload_718988 99999/fk4r51037p
etdadmin_upload_719049 99999/fk4md0893z
etdadmin_upload_720521 99999/fk4gm9jh0h
etdadmin_upload_720580 99999/fk4bz7j29g
etdadmin_upload_721046 99999/fk4766t86m
etdadmin_upload_721051 99999/fk43f63g5v
etdadmin_upload_722401 99999/fk4zp5ct8p
etdadmin_upload_722746 99999/fk4tx4p14d
```
